<?php declare(strict_types = 1);

// spell-check-ignore: 0every BQAAAA DRAUGR DUP FIL TRG VÐƷWİ aaa aaaaaa abcd asd attr4 azundris badvar bbbbbb dat fvar idx ivar loaddata5 maste mv mvi nosuchvar º Æ Ö Γåô Γê Γò Γòí ツ

namespace SqlFtw\Tests\Mysql;

trait NonFailures
{

    /** @var string[] */
    private static $knownNonFailures = [
        // test artifacts
        "-- error ER_WRONG_VALUE_FOR_VAR\n\n\nSET @@global.rpl_semi_sync_replica_enabled = @start_global_value;",
        "-- error ER_UNSUPPORTED_SQL_MODE\nINSERT INTO t1 VALUES (1);",
        "-- error ER_UNSUPPORTED_SQL_MODE\nCALL p1;",
        "-- error ER_GLOBAL_VARIABLE\nSET test_component.bool_sys_var=1;",
        "-- error ER_GLOBAL_VARIABLE\nSET test_component.enum_sys_var=\"LOW\";",
        "-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nset global ndb_dbg_check_shares=1;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSELECT test_set_system_variable_string(0, \"the_meaning_of_life\", \"42\", \"GLOBAL\");",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSELECT test_set_system_variable_string(1, \"the_meaning_of_life\", \"42\", \"GLOBAL\");",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSELECT test_set_system_variable_string(0, \"super_read_only\", \"gizmo\", \"GLOBAL\");",
        "-- disable_query_log\n-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nSET @innodb_change_buffering_debug_orig = @@innodb_change_buffering_debug;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nCREATE TABLE t1 (c1 INT) ENGINE= ARCHIVE;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nCREATE TEMPORARY TABLE t1 (c1 INT) ENGINE= ARCHIVE;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nALTER TABLE t1 ENGINE= ARCHIVE;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nCREATE TABLE t1(a int) ENGINE=ARCHIVE;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nCREATE TABLE t1(a int) ENGINE=BLACKHOLE;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nDROP TABLE t1;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\ncreate table t1 (id int) engine=FEDERATED;",
        "-- error ER_UNKNOWN_STORAGE_ENGINE\nalter table t1 engine=FEDERATED;",
        "-- error ER_WRONG_VALUE_FOR_VAR\ncall test_signal() $$",
        "-- error ER_WRONG_VALUE_FOR_VAR\ncall test_signal(\"Parameter string\", NULL) $$",
        "-- error ER_WRONG_VALUE_FOR_VAR\ncall test_signal(NULL, 1234) $$",
        "-- error 2\ncall peter_p3() $$",
        "-- error ER_WRONG_VALUE_FOR_VAR\ncall test_signal $$",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect f1(0)|",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect f1(f1(0))|",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect f1(f1(f1(0)))|",
        "-- error ER_UNSUPPORTED_PS\ncall p1()|",
        "-- error ER_SP_WRONG_NO_OF_FETCH_ARGS\ncall p()|",
        "-- error ER_WRONG_VALUE_FOR_VAR\nEXECUTE s USING @x;",
        "-- error 40000\ncall bigError();",
        "-- error ER_WRONG_VALUE\ncall p_16();",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL mysqlx_zstd_default_compression_level=1;", // depends on lib version
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET @@global.mysqlx_zstd_default_compression_level=2;",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL mysqlx_zstd_default_compression_level=-1;",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET @@global.mysqlx_zstd_default_compression_level=-2;",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL mysqlx_zstd_max_client_compression_level=1;",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET @@global.mysqlx_zstd_max_client_compression_level=2;",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL mysqlx_zstd_max_client_compression_level=-1;",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET @@global.mysqlx_zstd_max_client_compression_level=-2;",
        // sql_mode vs escaping
        "INSERT INTO t1 VALUES (\"1\\\"\"), (\"\\\"2\");",
        // no info on charset/engine ids. this is runtime error
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET CHARACTER_SET_CLIENT=17;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset session character_set_client=2048;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset session character_set_connection=2048;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset session character_set_database=2048;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset session character_set_filesystem=2048;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset session character_set_results = 2048;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset session character_set_server=2048;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nset character_set_client=9999999;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@character_set_client = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@character_set_connection = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@character_set_database = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@character_set_filesystem = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@character_set_results = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@character_set_server = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@global.character_set_client = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@global.character_set_connection = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@global.character_set_database = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@global.character_set_filesystem = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@global.character_set_results = 100;",
        "-- error ER_UNKNOWN_CHARACTER_SET\nSET @@global.character_set_server = 100;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.internal_tmp_mem_storage_engine = 123;",
        // multibyte not supported?
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@character_set_client = ucs2;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@character_set_client = utf16;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@character_set_client = utf32;",
        // ¯\_(ツ)_/¯
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = '+-> <()~*:\"\"&|';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = '0';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = '1 -><()~*:11&|';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = '# -><()~*:11&1';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = '1234567890ABCD';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = '+-> <((~*:\".&|';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = ' ';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = ENABLE;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = 'IGNORE';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.ft_boolean_syntax = ON;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global ft_boolean_syntax='@ -><()~*:\"\"@|';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global ft_boolean_syntax='+ -><()~*:\"\"@!|';",
        // implement gtid values
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.gtid_purged= '         -+11111111-1111-1111-1111-111111111111:9';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.gtid_purged= '         +-11111111-1111-1111-1111-111111111111:9';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_group_name= \"8a94f357-aab4-11df-86ab-invalid\";",
        // special rules for dynamic changes
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_commit_concurrency=0;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_commit_concurrency=1;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_commit_concurrency=42;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_commit_concurrency = 1;",
        "-- error ER_INCORRECT_GLOBAL_LOCAL_VAR\nSET @@GLOBAL.innodb_doublewrite=off;",
        "-- error ER_INCORRECT_GLOBAL_LOCAL_VAR\nSET @@GLOBAL.innodb_doublewrite=on;",
        // strict type handling
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_queries_not_using_indexes= 'true';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_queries_not_using_indexes= @badvar;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_slow_admin_statements= 'true';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_slow_admin_statements= @badvar;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_statements_unsafe_for_binlog= 'true';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_statements_unsafe_for_binlog= @badvar;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.offline_mode= 'true';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.unique_checks = \"True\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.unique_checks = \"False\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET sql_quote_show_create= _binary x'5452c39c45';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET sql_quote_show_create= _utf8 x'5452c39c45';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET sql_quote_show_create=_latin1 x'5452dc45';",
        // special format
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_ft_aux_table='Salmon';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_ft_aux_table =@a;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_ft_server_stopword_table='Salmon';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset session innodb_ft_user_stopword_table='Salmon';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset @@session.innodb_ft_user_stopword_table='Salmon';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_ft_user_stopword_table='Salmon';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_enable = aaa;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_enable = \"%lock*\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_enable=\"\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_enable=\"_\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_enable =0xee;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_disable =0xed;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\"/dir1\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\":\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\"l1:\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\":d1;;\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\":d1;d2\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\"l1:d1;l2:\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.innodb_redo_log_archive_dirs=\"l1:d1;l2:;\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_tmpdir=repeat('a',1000);",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"1234\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"-10000,10001,MY-10002\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"10000,-10001,MY-10002\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"10000,10001,-MY-10002\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\",10000,10001,MY-10002\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"10000,,10001,MY-10002\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"10000,10001,MY-10002,\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\",\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list=\"10000 10001\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list= CONCAT(REPEAT(\"ER_PARSER_TRACE,\",509),\"ER_PARSER_TRACE\");",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list= CONCAT(REPEAT(\"10000,\", 509), \"11111\");",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list='10000.123';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list='MY-10000#$%';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list='999';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list='MY-999';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_suppression_list='25000';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list='12345.124';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list='12345e5';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=abcd;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list='abcd';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=',';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=',10000,';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list='10000,';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=',10000';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list='10000,,10001';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=\"'10000'\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=CONCAT(\"'\",CONCAT('10000',\"'\"));",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_suppression_list=\"MY-0100000\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = -1;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = TAB;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = NIL;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = 'FIL';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = 'T';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = 'TABLE, FILE';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = ' TABLE,FILE';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = 0;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = 8;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_output = FALSE;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_output = 0;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset session optimizer_switch=\"index_merge\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset session optimizer_switch=\"foobar\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global optimizer_switch = 'e';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch ='b';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch = 0x6400ec62;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='default,index_merge';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='index_merge=index_merge';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='index_merge=on,but...';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='index_merge=';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='index_merge';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='on';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='index_merge=on,index_merge=off';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='index_merge_union=on,index_merge_union=default';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset optimizer_switch='default,index_merge=on,index_merge=off,default';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset session optimizer_trace=\"foobar\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset session optimizer_trace_features=\"foobar\";",
        "-- error ER_DUP_LIST_ENTRY\nSET @@global.session_track_system_variables= \"sql_mode,sql_mode\";",
        "-- error ER_DUP_LIST_ENTRY\nSET @@session.session_track_system_variables= \"sql_mode,sql_mode\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL mandatory_roles=\"foo,\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL mandatory_roles='``@`localhost`';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL innodb_ft_aux_table=\"test/t6\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_ft_server_stopword_table = \"not_defined\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_reset_all=0xe7;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_monitor_reset =0xe9;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\";log_sink_internal\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"log_sink_internal; log_filter_internal\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"log_filter_internal;,log_sink_internal\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"log_filter_internal log_sink_internal\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"azundris\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"log_sink_buffer\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_services= \"log_filter_internal; log_sink_internal; log_filter_internal; log_sink_json\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL log_error_services= \"log_sink_internal; log_sink_internal\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"log_sink_internal; log_sink_internal\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.log_error_services=\"log_filter_dragnet; log_filter_dragnet\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='ELSE drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='DRAUGR.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN set b==2.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF err_symbol=='ER_STARTUP THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF err_symbol==ER_STARTUP' THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF err_symbol=='ER_STARTUP\\\" THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF err_symbol==\\\"ER_STARTUP' THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF misc_cstring=='1' THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF a=='1' THEN set misc_cstring:='abc'.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF EXISTS misc_cstring THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF EXISTS foo THEN set component:=1.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF EXISTS foo THEN set component:=1..5.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF EXISTS foo THEN set prio:=1.5.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF err_symbol==ER_STARTUP\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF NOT field THEN action.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF err_symbol==ER_STARTUP THEN drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF err_code==\"ER_STARTUP\" THEN drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 AND b==3 THEN unset.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF EXISTS a>0 THEN drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF EXISTS a THEN drop';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF EXISTS field THEN AND.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF EXISTS field DROP.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN set.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN set b.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN set b:=.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN set b:=.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN set :=2.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN drop';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF thread>=INFORMATION THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=INFORMATION THEN set thread:=ERROR.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=NOUGAT THEN drop.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=9999 THEN throttle 1/1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 .\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=9999 THEN drop. IF EXISTS source_line THEN unset source_line. IF err_code == 001045 THEN throttle 1/1.1.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=9999 THEN throttle 111/604801.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=9999 THEN throttle 111/0.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=\"IF prio>=9999 THEN throttle 111/-1.\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN drop a.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN throttle a.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN throttle 1.5.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN throttle 1/b.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN throttle a/.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN throttle -1/2.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN throttle 0/2.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='ELSE.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 ELSE.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN drop ELSE drop ELSE drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN drop ELSE scream.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a==2 THEN drop ELSE.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF .';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF EXISTS a THEN.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF a!!b THEN drop.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules='IF EXISTS.';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules= REPEAT(\"IF prio>9 THEN drop. \", 1025);",
        "-- error 0,ER_WRONG_VALUE_FOR_VAR\nSET @@global.dragnet.log_error_filter_rules=@save_filters;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.syseventlog.facility= \"9\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.syseventlog.facility= \"local8\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.syseventlog.tag= \"path/like\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.event_scheduler = DISABLED;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET PERSIST event_scheduler=DISABLED;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL event_scheduler=DISABLED;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL event_scheduler=2;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.event_scheduler = 2;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSIGNAL SQLSTATE 'HY000' SET MYSQL_ERRNO = 65536;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSIGNAL SQLSTATE 'HY000' SET MYSQL_ERRNO = 99999;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSIGNAL SQLSTATE 'HY000' SET MYSQL_ERRNO = 4294967295;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSIGNAL SQLSTATE 'HY000' SET MYSQL_ERRNO = 0;",
        "-- error ER_UNKNOWN_LOCALE\nset lc_time_names=concat('de','+','DE');",
        "-- error ER_UNKNOWN_LOCALE\nset lc_time_names=-1;",
        "-- error ER_UNKNOWN_LOCALE\nset lc_time_names=111;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = 111;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@session.lc_time_names=EE;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@global.lc_time_names=EE;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = en_EN;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = US_en;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = -1;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = 'en US';",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = 'enUS';",
        "-- error ER_UNKNOWN_LOCALE\nSET @@lc_time_names = ON;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@global.lc_time_names = en_EN;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@global.lc_time_names = US_en;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@global.lc_time_names = -1;",
        "-- error ER_UNKNOWN_LOCALE\nSET @@global.lc_time_names = 'enUS';",
        "-- error ER_UNKNOWN_LOCALE\nSET @@global.lc_time_names = ON;",
        // file paths
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.keyring_file_data= '../../../../../bad_dir/bad_keyring_file_data/';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.keyring_file_data='/';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.keyring_file_data='/keyring/';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.keyring_file_data= 'MYSQL_test_invalid/dir/';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_tmpdir='wrong_value';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global innodb_tmpdir = @@global.datadir;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset global general_log_file='/not existing path/log.master';",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL general_log_file= CONCAT('/not existing path/log.maste', 'r');",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL slow_query_log_file= CONCAT('/not existing path/log.maste', 'r');",
        "-- error ER_WRONG_VALUE\nCREATE TABLE t4 (a int, b text) TABLESPACE=innodb_file_per_table DATA DIRECTORY='test';",
        "-- error ER_WRONG_VALUE\ncreate table mysqltest.t9 (a int not null auto_increment, b char(16) not null, primary key (a)) \nengine=myisam index directory=\"not-hard-path\";",
        // some user restrictions; deprecated
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_delayed_threads = 1000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_delayed_threads = 1;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_delayed_threads = 1025;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_delayed_threads = 16384;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@max_delayed_threads = 100000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET max_delayed_threads = 1024;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_insert_delayed_threads = 1000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_insert_delayed_threads = 1;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_insert_delayed_threads = 1025;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@session.max_insert_delayed_threads = 16384;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@max_insert_delayed_threads = 100000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET max_insert_delayed_threads = 1024;",
        // WTF?
        "-- error ER_EMPTY_QUERY\n ;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.connection_control_min_connection_delay= 11000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@global.connection_control_max_connection_delay= 10000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@GLOBAL.group_replication_clone_threshold= 9223372036854775808;", // probably lying in doc about the limits...
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_flow_control_min_quota= 1000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_flow_control_min_recovery_quota= 1000;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_flow_control_max_quota= 1;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_force_members= \"127.0.0.1:10000\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_force_members= \"127.0.0.1:10001\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_force_members= \"256.256.256.777:1234\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_force_members= \"\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_gtid_assignment_block_size= 9223372036854775808;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_message_cache_size= 4294967296;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@GLOBAL.group_replication_member_weight= 100;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@GLOBAL.group_replication_recovery_compression_algorithms= \"ZLIB\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET @@GLOBAL.group_replication_recovery_compression_algorithms= \"ZSTD\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL GROUP_REPLICATION_COMMUNICATION_DEBUG_OPTIONS=\",,,\";", // set
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL GROUP_REPLICATION_COMMUNICATION_DEBUG_OPTIONS=\",,,,,\";",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_single_primary_mode= TRUE;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_enforce_update_everywhere_checks= TRUE;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL group_replication_allow_local_disjoint_gtids_join= ON;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSELECT @@GLOBAL.group_replication_allow_local_disjoint_gtids_join;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nSET GLOBAL group_replication_view_change_uuid = \"\";", // PERSIST_ONLY is ok
        "-- error 0,ER_WRONG_VALUE\nSELECT 1 FROM t1 WHERE (@b IN ( SELECT a FROM t1 )) = a;",
        "-- error 0\nALTER TABLE t1 algorithm=copy, ADD c CHAR(19);",
        // WTF?!
        "-- error ER_PARSE_ERROR\nselect hex(weight_string('a' as char(0)));",
        "-- error ER_PARSE_ERROR\nselect * from t1 where match b against ('+aaaaaa @bbbbbb' in boolean mode);",
        "-- error ER_PARSE_ERROR\nSELECT * FROM t1 WHERE MATCH(a) AGAINST(\"*\");",
        "-- error ER_PARSE_ERROR\nSELECT a FROM t1 WHERE MATCH (a) AGAINST (CONCAT(0x00, '\"', 'i', 'n', 'n', 'o', 'd', 'b', ' ', '$', 's', 't', 'o', 'r', 'a', 'g', 'e', '\"','@', '4', 0x00) IN BOOLEAN MODE);",
        "-- error ER_PARSE_ERROR\nSELECT b FROM t1 WHERE MATCH (b) AGAINST (CONCAT(0x00, '\"', 'i', 'n', 'n', 'o', 'd', 'b', ' ', '$', 's', 't', 'o', 'r', 'a', 'g', 'e', '\"','@', '4', 0x00) IN BOOLEAN MODE);",
        "-- error ER_PARSE_ERROR\nSELECT c FROM t1 WHERE MATCH (c) AGAINST (CONCAT(0x00, '\"', 'i', 'n', 'n', 'o', 'd', 'b', ' ', '$', 's', 't', 'o', 'r', 'a', 'g', 'e', '\"','@', '4', 0x00) IN BOOLEAN MODE);",
        "-- error ER_PARSE_ERROR\nSELECT ANY_VALUE(MATCH (a) AGAINST ('<' IN BOOLEAN MODE)), COUNT(*) FROM t;",
        "-- error ER_PARSE_ERROR\nselect * from t1 where MATCH(a,b) AGAINST(\"+-VÐƷWİ\" IN BOOLEAN MODE);",
        "-- error ER_FUNCTION_NOT_DEFINED\nCREATE TABLE t2 (\n        id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,\n        title VARCHAR(200),\n\tFULLTEXT INDEX ft_title (title) WITH PARSER ngram\n) ENGINE=InnoDB DEFAULT CHARACTER SET gb2312 COLLATE gb2312_chinese_ci;",
        // debug (valid syntax, invalid circumstances)
        "-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nSET @aux = @@session.debug;",
        "-- error ER_RESTART_SERVER_FAILED\nRESTART;",
        "-- error 1,1\nCREATE TABLE s.t (pk INTEGER PRIMARY KEY);",
        "-- error 2\ncall peter_p3();",
        "-- error 18\ncall test_signal;",
        "-- error 3\ncall test_signal;",
        "-- error 10000\n  call po_add_order_line (@my_po, 1, 999, 1);",
        "-- error 10000\n  call po_add_order_line (99, 1, 100, 1);",
        "-- error 10000\ncall po_create_order(\"M\", 7, @my_po);",
        "-- error ER_COND_ITEM_TOO_LONG\ncall p2;",
        "-- error ER_COND_ITEM_TOO_LONG\ncall p3;",
        "-- error ER_UNSUPPORTED_PS\ncall p1();",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect f1(0);",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect f1(f1(0));",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect f1(f1(f1(0)));",
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\ninsert into t1 values (0);",
        "-- error ER_SP_CURSOR_NOT_OPEN\ncall p();",
        "-- error ER_SP_WRONG_NO_OF_FETCH_ARGS\ncall p();",
        "-- error ER_PARSE_ERROR\nCREATE TRIGGER tr16 AFTER UPDATE ON t1 FOR EACH ROW INSERT INTO t1 VALUES (1);",
        "-- error ER_PARSE_ERROR\nINSERT INTO t1 VALUES (1);",
        "-- error ER_PARSE_ERROR\nDELETE FROM t1;",
        "-- error ER_PARSE_ERROR\nUPDATE t1 SET a = 1 WHERE a = 1;",
        "-- error ER_PARSE_ERROR\nINSERT INTO t2 VALUES (1);",
        "-- error ER_PARSE_ERROR\nINSERT INTO th1 VALUES(1);",
        "-- error ER_WINDOW_FRAME_ILLEGAL\nEXECUTE p USING @p2, @p1;",
        "-- error ER_WINDOW_FRAME_ILLEGAL\nEXECUTE p USING @p1, @p2;",
        "-- error ER_WINDOW_FRAME_ILLEGAL\nEXECUTE p USING @p1;",
        "-- error ER_WINDOW_FRAME_ILLEGAL\nEXECUTE stmt;",
        "-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nSET DEBUG = \"\";",
        "-- error ER_NOT_SUPPORTED_YET\nALTER TABLE t_stmt ADD COLUMN b INT;",
        "-- error ER_PARSE_ERROR\nINSERT INTO t1  VALUES (),();",
        "-- error ER_PARSE_ERROR\nINSERT INTO t1(c1)  SELECT 1 FROM DUAL;",
        "-- error ER_PARSE_ERROR\nLOAD DATA INFILE '../../std_data/loaddata5.dat'\n INTO TABLE t1 FIELDS TERMINATED BY '' ENCLOSED BY '' (c1) ;",
        "-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nSET @innodb_change_buffering_debug_orig = @@innodb_change_buffering_debug;",
        "-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL innodb_change_buffering_debug = 1;",
        "-- error 0, ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL innodb_change_buffering_debug = 0;",
        "-- disable_query_log\n\n\n\n\n-- error 0,ER_UNKNOWN_SYSTEM_VARIABLE\nSET @innodb_change_buffering_debug_orig = @@innodb_change_buffering_debug;",
        "-- disable_query_log\n-- error 0, ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL innodb_change_buffering_debug = @innodb_change_buffering_debug_orig;",
        "-- error 0, ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL innodb_change_buffering_debug = @innodb_change_buffering_debug_orig;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSELECT @@global.keyring_file_data;",
        "-- error ER_NOT_SUPPORTED_YET\ninsert into t1 values('{\"asd\":1}');",
        "-- error ER_NOT_SUPPORTED_YET\ninsert into t1 values('true');",
        "-- error ER_NOT_SUPPORTED_YET\nalter table t2 rename t1, add attr4 int;",
        "-- error ER_TOO_LONG_IDENT\nCREATE TABLE t2 (\n  a int\n) ENGINE=NDB;",
        "-- error ER_PARSE_ERROR\nPREPARE test_stmt2 FROM @s;",
        "-- error ER_PARSE_ERROR\nSELECT 'Fail, please', 'a';",
        "-- error ER_MASTER_INFO\nRESET SLAVE;",
        "-- error ER_CANT_USE_GTID_ONLY_WITH_GTID_MODE_NOT_ON\nSTART SLAVE;",
        "-- error ER_MASTER_INFO\nstart slave sql_thread;",
        "-- error ER_MASTER_INFO\nstart slave;",
        "-- error ER_MASTER_INFO\nRESET SLAVE ALL;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nCALL p1('test');",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nCALL p2();",
        // valid on real DB
        "-- error ER_USER_LOCK_WRONG_NAME\nSELECT STD(IS_FREE_LOCK(0x2ADA5C38)),1 FROM t1 WHERE a+(EXISTS(SELECT 1));",
        "-- error 0,ER_NOT_SUPPORTED_YET\nSELECT * FROM (\n  SELECT a, JSON_ARRAYAGG(a) OVER () AS b FROM t1\n) AS d1\nWHERE (a,b) IN (\n  SELECT a, JSON_ARRAYAGG(a) OVER () AS b FROM t1\n);",
        "-- error ER_PARSE_ERROR\nCREATE PROCEDURE sp1( )\n BEGIN\n   declare continue handler for sqlstate '02000' set @var2 = 1;\nEND//",
        "-- error ER_PARSE_ERROR\nCREATE PROCEDURE sp1( )\n BEGIN\n   declare exit handler for sqlstate '02000' set @var2 = 1;\nEND//",
        // binlog
        "-- error ER_SYNTAX_ERROR\nBINLOG '\nDl1YRxMBAAAAKQAAADQBAAAAABAAAAAAAAAABHRlc3QAAnQxAAEDAAE=\nDl1YRxcBAAAAIgAAAFYBAAAQABAAAAAAAAEAAf/+BQAAAA==\n';",
        "-- error ER_BASE64_DECODE_ERROR\nBINLOG '123';",
        "-- error ER_BASE64_DECODE_ERROR\nBINLOG '-2079193929';",
        "-- error ER_BASE64_DECODE_ERROR\nBINLOG 'x├ºΓåô%~ΓêÖDΓòÆ╞ÆΓòí';",
        // checks for collation files
        "-- error ER_UNKNOWN_COLLATION\nALTER TABLE t1 ADD COLUMN (j INTEGER);",
        "-- error ER_UNKNOWN_COLLATION\nSELECT * FROM t1;",
        "-- error ER_UNKNOWN_COLLATION\nINSERT INTO t1 VALUES (1);",
        "-- error ER_UNKNOWN_COLLATION\nSHOW CREATE TABLE t1;",
        // multiple ORDER BY
        "-- error ER_NOT_SUPPORTED_YET\n((SELECT 1 FROM t1 ORDER BY 1) ORDER BY 1) ORDER BY 1;",
        "-- error ER_NOT_SUPPORTED_YET\nEXPLAIN ((SELECT * FROM t3 ORDER BY a LIMIT 3)\n            ORDER BY b DESC LIMIT 2)\n                ORDER BY c LIMIT 1;",
        "-- error ER_PARSE_ERROR,ER_NOT_SUPPORTED_YET\n((SELECT * FROM t1 ORDER BY i) ORDER BY i) ORDER BY i;",
        // multiple LIMIT (OK on real DB)
        "-- error 0,ER_PARSE_ERROR\n((SELECT * FROM t1 LIMIT 1) LIMIT 2) LIMIT 3;",
        // operator associativity etc.
        "-- error ER_PARSE_ERROR\nselect TRUE IS TRUE IS TRUE IS TRUE;",
        "-- error ER_PARSE_ERROR\nselect FALSE IS NOT TRUE IS NOT TRUE IS NOT TRUE;",
        "-- error ER_PARSE_ERROR\nselect NULL IS FALSE IS FALSE IS FALSE;",
        "-- error ER_PARSE_ERROR\nselect TRUE IS NOT FALSE IS NOT FALSE IS NOT FALSE;",
        "-- error ER_PARSE_ERROR\nselect FALSE IS UNKNOWN IS UNKNOWN IS UNKNOWN;",
        "-- error ER_PARSE_ERROR\nselect TRUE IS NOT UNKNOWN IS NOT UNKNOWN IS NOT UNKNOWN;",
        // types on aggregate functions
        "-- error ER_PARSE_ERROR\nSELECT id, sex, LEAD(id, -1) RESPECT NULLS OVER () FROM t1;",
        "-- error ER_PARSE_ERROR\nSELECT id, sex, LEAD(id, 1.2) RESPECT NULLS OVER () FROM t1;",
        "-- error ER_PARSE_ERROR\nSELECT id, sex, LEAD(id, 'a') RESPECT NULLS OVER () FROM t1;",
        "-- error ER_PARSE_ERROR\nSELECT id, sex, LEAD(id, NULL) RESPECT NULLS OVER () FROM t1;",
        // need to parse prepared statement
        "-- error ER_UNSUPPORTED_PS\nPREPARE stmt1 FROM @sql1;",
        "-- error ER_UNSUPPORTED_PS\nPREPARE stmt2 FROM 'SELECT @@warning_count';",
        "-- error ER_UNSUPPORTED_PS\nPREPARE stmt2 FROM 'SELECT @@error_count';",
        "-- error ER_UNSUPPORTED_PS\nPREPARE stmt FROM \"CREATE TABLE t1 (f1 INT) START TRANSACTION\";",
        "-- error ER_TRG_DOES_NOT_EXIST\nexecute stmt;",
        // not checking var content on PREPARE
        "-- error ER_PARSE_ERROR\nprepare stmt1 from @nosuchvar;",
        "-- error ER_PARSE_ERROR\nprepare stmt1 from @ivar;",
        "-- error ER_PARSE_ERROR\nprepare stmt1 from @fvar;",
        "-- error ER_PARSE_ERROR\nprepare stmt1 from @arg01;",
        // recursion or something...
        "-- error ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG\nselect func_1(), func_1(), func_1() from dual;",
        // needs validating charsets
        "-- source include/ctype_filesort.inc\n-- source include/ctype_like_escape.inc\n\n\n\n\n\n\n-- error ER_PARSE_ERROR\nCREATE TABLE \x84a (a int);",
        // needs analyzing expressions
        "-- error ER_PARSE_ERROR\nCREATE TABLE t1 (\na int not null,\nb int not null,\nc int not null,\nprimary key(a,b))\npartition by hash (rand(a))\npartitions 2\n(partition x1, partition x2);",
        "-- error ER_PARSE_ERROR\nCREATE TABLE t1 (\na int not null,\nb int not null,\nc int not null,\nprimary key(a,b))\npartition by range (rand(a))\npartitions 2\n(partition x1 values less than (0), partition x2 values less than (2));",
        "-- error ER_PARSE_ERROR\nCREATE TABLE t1 (\na int not null,\nb int not null,\nc int not null,\nprimary key(a,b))\npartition by list (rand(a))\npartitions 2\n(partition x1 values in (1), partition x2 values in (2));",
        "-- error ER_PARSE_ERROR\nCREATE TABLE t1 (\na int not null,\nb int not null,\nc int not null,\nprimary key (a,b))\npartition by key (a)\nsubpartition by hash (rand(a+b));",
        "-- error ER_PARSE_ERROR\ncreate table t1 (a int)\npartition by hash (rand(a));",
        "-- error ER_PARSE_ERROR\ncreate table t1 (a int)\npartition by hash(CURTIME() + a);",
        "-- error ER_PARSE_ERROR\ncreate table t1 (a int)\npartition by hash (NOW()+a);",
        "-- error ER_PARSE_ERROR\nALTER TABLE t1 ADD PARTITION\n(PARTITION p3_a VALUES IN ((1 + 1 + 1), \"a0\"));",
        "-- error ER_PARSE_ERROR\nSELECT CURTIME(-1);",
        "-- error ER_PARSE_ERROR\nSELECT SYSDATE(-1);",
        "-- error ER_PARSE_ERROR\nSELECT NOW(-1);",
        "-- error ER_NOT_SUPPORTED_YET\nSELECT SUM(DISTINCT b) OVER () FROM t;",
        "-- error ER_NOT_SUPPORTED_YET\nselect cast('[1,2,3]' as unsigned array);",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1 as select cast('[1,2,3]' as unsigned array);",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t(j json, gc json as (cast(j->'$[*]' as unsigned array)));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t(j json, gc json as\n  ((concat(cast(j->'$[*]' as unsigned array),\"x\"))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1(j json, key i1((cast(j->\"\$\" as json array))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1(j json, key i1((cast(j->\"\$\" as char array))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1(j json, key i1((cast(j->\"\$\" as binary array))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1(j json, key i1((cast(j->\"\$\" as float array))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1(j json, key i1((cast(j->\"\$\" as double array))));",
        "-- error ER_NOT_SUPPORTED_YET\nCREATE TABLE t1 (f1 json, key mvi((cast(cast(f1 as unsigned array) as unsigned array))));",
        "-- error ER_NOT_SUPPORTED_YET\nCREATE TABLE t(x INT, KEY k ((1 AND CAST(JSON_ARRAY(X) AS UNSIGNED ARRAY))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table col(doc json,\n  key i1((cast(doc->'$.text' as char(10) array)),\n         (cast(doc->'$.integer' as signed array))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t1 (j json, key mv_idx_char ((cast(j as char(16384) array))));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate table t (j json default (cast(json_object() as unsigned array)));",
        "-- error ER_NOT_SUPPORTED_YET\ncreate index i1 on t1((cast(f1->\"\$\" as YEAR array)));",
        "-- error ER_NOT_SUPPORTED_YET\nCREATE TABLE t_copy AS SELECT * FROM t;",
        "-- error ER_NOT_SUPPORTED_YET\nSELECT JSON_SCHEMA_VALID('{\n  \"type\": \"object\",\n  \"properties\": { \"\$ref\": \"http://example.com\" }\n}','\n{\n  \"latitude\": 63.444697\n}') AS invalid;",
        "-- error ER_PARSE_ERROR\nSELECT JSON_VALUE('{}', NULL);",
        // needs analysing param types
        "-- error ER_PARSE_ERROR\ncreate procedure p1(p1 date, p2 date) select * from t1 limit p1, p2;",
        "-- error ER_PARSE_ERROR\ncreate procedure p1(p1 integer, p2 float) select * from t1 limit p1, p2;",
        "-- error ER_PARSE_ERROR\ncreate procedure p1(p1 integer, p2 char(1)) select * from t1 limit p1, p2;",
        "-- error ER_PARSE_ERROR\ncreate procedure p1(p1 varchar(5), p2 char(1)) select * from t1 limit p1, p2;",
        "-- error ER_PARSE_ERROR\ncreate procedure p1(p1 decimal, p2 decimal) select * from t1 limit p1, p2;",
        "-- error ER_PARSE_ERROR\ncreate procedure p1(p1 double, p2 double) select * from t1 limit p1, p2;",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 date, p2 date)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend;",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 integer, p2 float)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend;",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 integer, p2 char(1))\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend;",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 varchar(5), p2 char(1))\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend;",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 decimal, p2 decimal)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend;",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 double, p2 double)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend;",
        "-- error ER_PARSE_ERROR\nSELECT myfunc_int(test.fn(MIN(b) xx)) as c FROM t1 GROUP BY a;",
        "-- error ER_PARSE_ERROR\nSELECT id, NTILE(NULL) OVER w FROM t1 WINDOW w AS (ORDER BY id);",
        "-- error ER_PARSE_ERROR\nEXPLAIN FORMAT=JSON SELECT id, NTILE(NULL) OVER w FROM t1 WINDOW w AS (ORDER BY id);",
        "-- error ER_PARSE_ERROR\nDO NTILE(MAX(NOT 1)) OVER();",
        "-- error ER_PARSE_ERROR\nSELECT ST_X(ST_POINTFROMWKB(ST_ASWKB(POINT(1))));",
        "-- error ER_PARSE_ERROR\nSELECT ST_Y(ST_POINTFROMWKB(ST_ASWKB(POINT(1))));",
        "-- error ER_PARSE_ERROR\nSELECT ST_ASTEXT(ST_X(ST_POINTFROMWKB(ST_ASWKB(POINT(1)), 5)));",
        "-- error ER_PARSE_ERROR\nSELECT ST_ASTEXT(ST_Y(ST_POINTFROMWKB(ST_ASWKB(POINT(1)), 5)));",
        // parse error misuse
        "-- error ER_PARSE_ERROR\nALTER TABLE t1 ADD PARTITION\n(PARTITION p2 VALUES IN ((71),(72),(73),(74),(75),(76),(77),(78),(79),(80),\n                         (81),(82),(83),(84),(85),(86),(87),(88),(89),(90)));",
        // conflicting aliases
        "-- error ER_PARSE_ERROR\nDELETE FROM t1 alias USING t1, t2 alias WHERE t1.a = alias.a;",
        "-- error ER_UNKNOWN_TABLE\nDELETE FROM t1, t2 USING t1, t2 alias WHERE t1.a = alias.a;",
        "-- error ER_PARSE_ERROR\nDELETE FROM db1.t1 alias USING db1.t1, db2.t1 alias WHERE db1.t1.a = alias.a;",
        "-- error ER_PARSE_ERROR\nDELETE FROM t1 alias USING t1 alias WHERE a = 2;",
        // table + check name
        "-- error ER_TOO_LONG_IDENT\nRENAME TABLE t1 TO t123456789012345678901234567890123456789012345678901234567890;",
        "-- error ER_TOO_LONG_IDENT\nCREATE TABLE t123456789012345678901234567890123456789012345678901234567890(f1 INT CHECK(f1 < 10));",
        "-- error ER_TOO_LONG_IDENT\nALTER TABLE t123456789012345678901234567890123456789012345678901234567890 ADD CONSTRAINT CHECK (f1 < 10);",
        // table + fk name
        "-- error ER_TOO_LONG_IDENT\nRENAME TABLE t2 TO t123456789012345678901234567890123456789012345678901234567;",
        "-- error ER_TOO_LONG_IDENT\nCREATE TABLE t123456789012345678901234567890123456789012345678901234567(\n  a INT, FOREIGN KEY (a) REFERENCES t1(a));",
        "-- error ER_TOO_LONG_IDENT\nALTER TABLE name567890123456789012345678901234567890123456789012345678901234\nADD FOREIGN KEY(b) REFERENCES t1(a);",
        // not checking components
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSELECT @@syseventlog.tag;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL syseventlog.include_pid = OFF;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSET GLOBAL syseventlog.facility = \"local1\";",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSET @save_filters= @@global.dragnet.log_error_filter_rules;",
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSET @@global.dragnet.log_error_filter_rules= DEFAULT;",
        // depends on plugin
        "-- error ER_UNKNOWN_SYSTEM_VARIABLE\nSELECT @@GLOBAL.validate_password_length;",
        // depends on OS
        "-- error ER_FEATURE_UNSUPPORTED\nCREATE RESOURCE GROUP test TYPE=USER VCPU=1-3 THREAD_PRIORITY=5;",
        "-- error ER_FEATURE_UNSUPPORTED\nALTER RESOURCE GROUP test VCPU=0;",
        "-- error ER_FEATURE_UNSUPPORTED\nDROP RESOURCE GROUP test;",
        // scopes & variables
        "-- error ER_VAR_DOES_NOT_EXIST\nRESET PERSIST max_connections;",
        "-- error ER_VAR_DOES_NOT_EXIST\nRESET PERSIST sort_buffer_size;",
        // NDB
        "-- error ER_NOT_SUPPORTED_YET\nALTER TABLE t1\n  ADD COLUMN c INT,\n  RENAME TO t1_renamed;",
        // whitespace dependent function name parsing
        "-- error ER_PARSE_ERROR\ncreate table BIT_AND(a int);",
        "-- error ER_PARSE_ERROR\ncreate table BIT_OR(a int);",
        "-- error ER_PARSE_ERROR\ncreate table BIT_XOR(a int);",
        "-- error ER_PARSE_ERROR\ncreate table CAST(a int);",
        "-- error ER_PARSE_ERROR\ncreate table COUNT(a int);",
        "-- error ER_PARSE_ERROR\ncreate table CURDATE(a int);",
        "-- error ER_PARSE_ERROR\ncreate table CURTIME(a int);",
        "-- error ER_PARSE_ERROR\ncreate table DATE_ADD(a int);",
        "-- error ER_PARSE_ERROR\ncreate table DATE_SUB(a int);",
        "-- error ER_PARSE_ERROR\ncreate table EXTRACT(a int);",
        "-- error ER_PARSE_ERROR\ncreate table GROUP_CONCAT(a int);",
        "-- error ER_PARSE_ERROR\ncreate table MAX(a int);",
        "-- error ER_PARSE_ERROR\ncreate table MID(a int);",
        "-- error ER_PARSE_ERROR\ncreate table MIN(a int);",
        "-- error ER_PARSE_ERROR\ncreate table NOW(a int);",
        "-- error ER_PARSE_ERROR\ncreate table POSITION(a int);",
        "-- error ER_PARSE_ERROR\ncreate table STD(a int);",
        "-- error ER_PARSE_ERROR\ncreate table STDDEV(a int);",
        "-- error ER_PARSE_ERROR\ncreate table STDDEV_POP(a int);",
        "-- error ER_PARSE_ERROR\ncreate table STDDEV_SAMP(a int);",
        "-- error ER_PARSE_ERROR\ncreate table SUBSTR(a int);",
        "-- error ER_PARSE_ERROR\ncreate table SUBSTRING(a int);",
        "-- error ER_PARSE_ERROR\ncreate table SUM(a int);",
        "-- error ER_PARSE_ERROR\ncreate table SYSDATE(a int);",
        "-- error ER_PARSE_ERROR\ncreate table TRIM(a int);",
        "-- error ER_PARSE_ERROR\ncreate table VARIANCE(a int);",
        "-- error ER_PARSE_ERROR\ncreate table VAR_POP(a int);",
        "-- error ER_PARSE_ERROR\ncreate table VAR_SAMP(a int);",
        // with set SQL_MODE='IGNORE_SPACE'
        "-- error ER_PARSE_ERROR\ncreate table BIT_AND (a int);",
        "-- error ER_PARSE_ERROR\ncreate table BIT_OR (a int);",
        "-- error ER_PARSE_ERROR\ncreate table BIT_XOR (a int);",
        "-- error ER_PARSE_ERROR\ncreate table CAST (a int);",
        "-- error ER_PARSE_ERROR\ncreate table COUNT (a int);",
        "-- error ER_PARSE_ERROR\ncreate table CURDATE (a int);",
        "-- error ER_PARSE_ERROR\ncreate table CURTIME (a int);",
        "-- error ER_PARSE_ERROR\ncreate table DATE_ADD (a int);",
        "-- error ER_PARSE_ERROR\ncreate table DATE_SUB (a int);",
        "-- error ER_PARSE_ERROR\ncreate table EXTRACT (a int);",
        "-- error ER_PARSE_ERROR\ncreate table GROUP_CONCAT (a int);",
        "-- error ER_PARSE_ERROR\ncreate table MAX (a int);",
        "-- error ER_PARSE_ERROR\ncreate table MID (a int);",
        "-- error ER_PARSE_ERROR\ncreate table MIN (a int);",
        "-- error ER_PARSE_ERROR\ncreate table NOW (a int);",
        "-- error ER_PARSE_ERROR\ncreate table POSITION (a int);",
        "-- error ER_PARSE_ERROR\ncreate table STD (a int);",
        "-- error ER_PARSE_ERROR\ncreate table STDDEV (a int);",
        "-- error ER_PARSE_ERROR\ncreate table STDDEV_POP (a int);",
        "-- error ER_PARSE_ERROR\ncreate table STDDEV_SAMP (a int);",
        "-- error ER_PARSE_ERROR\ncreate table SUBSTR (a int);",
        "-- error ER_PARSE_ERROR\ncreate table SUBSTRING (a int);",
        "-- error ER_PARSE_ERROR\ncreate table SUM (a int);",
        "-- error ER_PARSE_ERROR\ncreate table SYSDATE (a int);",
        "-- error ER_PARSE_ERROR\ncreate table TRIM (a int);",
        "-- error ER_PARSE_ERROR\ncreate table VARIANCE (a int);",
        "-- error ER_PARSE_ERROR\ncreate table VAR_POP (a int);",
        "-- error ER_PARSE_ERROR\ncreate table VAR_SAMP (a int);",
        // input validations
        "-- error ER_WRONG_VALUE\nSELECT count(*) FROM t1 WHERE c2='10:45:15' OR c2='2009-01-32' OR c2='2009-02-30' OR c2='2009-04-31' OR c2='2009-06-31' OR c2='2009-09-31' /* returns 0 */;",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE c2='0000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE c1='0000-00-00' OR c2='0000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE c1='0000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT count(*) FROM t1 WHERE c1='2001-01-09 24:59:59' AND c2='2009-01-10 23:60:59';",
        "-- error ER_WRONG_VALUE\nSELECT count(*) FROM t1 WHERE c2='2001-01-11 23:59:60' /* returns 0 */;",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE c1='0000-00-00 00:00:00' OR c2='0000-00-00 00:00:00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE c2='0000-00-00 00:00:00';",
        "-- error ER_WRONG_VALUE\nexplain\nselect * from t1 where date_field < '9999-99-99';",
        "-- error ER_WRONG_VALUE\nselect * from t1 where date_field < '9999-99-99';",
        "-- error ER_WRONG_VALUE\nexplain\nselect * from t1 where date_field > '9999-99-99';",
        "-- error ER_WRONG_VALUE\nselect * from t1 where date_field > '9999-99-99';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE d <= '2013-02-32';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE d <= '2013-02-30';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE d >= '0000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE d >= 'wrong-date';",
        "-- error ER_WRONG_VALUE\ncreate event e_26 on schedule at NULL disable do set @a = 5;",
        "-- error ER_WRONG_VALUE\ncreate event e_26 on schedule at 'definitely not a datetime' disable do set @a = 5;",
        "-- error ER_WRONG_VALUE\ncreate event e_55 on schedule at 99990101000000 do drop table t;",
        "-- error ER_WRONG_VALUE\ncreate event e_55 on schedule every 10 hour starts 99990101000000 do drop table t;",
        "-- error ER_WRONG_VALUE\ncreate event e_55 on schedule at 10000101000000 do drop table t;",
        "-- error ER_WRONG_VALUE\ncreate event e_55 on schedule every 10 hour starts 10000101000000 do drop table t;",
        "-- error ER_WRONG_VALUE\nCREATE EVENT new_event ON SCHEDULE AT \"every day\" DO SELECT 1;",
        "-- error ER_WRONG_VALUE\nCREATE EVENT new_event ON SCHEDULE AT \"0every day\" DO SELECT 1;",
        "-- error ER_WRONG_VALUE\nWITH cte1 AS\n(SELECT(replace(md5(0x9025c5c7),\n                    convert((1) using utf8),\n                    (!(cast((connection_id()) AS char(20)))))) AS a1 FROM t0022)\nSELECT cte1.a1\nFROM cte1 WHERE cte1.a1 = from_unixtime(1537000917);",
        "-- error ER_WRONG_VALUE\nSELECT ST_AsWKB(ST_GeomFromText('POINT(0 0)')) > (SELECT b FROM t) AS result;",
        "-- error ER_WRONG_VALUE\nALTER USER 'wl7131' PASSWORD EXPIRE INTERVAL 0 DAY;",
        "-- error ER_WRONG_VALUE\nEXPLAIN SELECT * FROM t1 WHERE col2 < \"\";",
        "-- error ER_WRONG_VALUE\nEXPLAIN SELECT * FROM t1 WHERE a = '0000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE a = '0000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t2 WHERE a = '0000-00-00';",
        "-- error ER_WRONG_VALUE\nEXPLAIN SELECT * FROM t1 WHERE a = '1000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t1 WHERE a = '1000-00-00';",
        "-- error ER_WRONG_VALUE\nSELECT * FROM t2 WHERE a = '1000-00-00';",
        "-- error ER_WRONG_VALUE\nDELETE IGNORE  FROM t1 WHERE dt1 = '0000-00-01 00:00:01';",
        // runtime
        "-- error ER_WRONG_VALUE\nCREATE TABLE t3 (id INT) INDEX DIRECTORY = 'test';",
        "-- error ER_WRONG_VALUE\nCREATE TABLE t4 (id INT NOT NULL, name VARCHAR(30))\nENGINE = InnoDB\nPARTITION BY RANGE (id) (\nPARTITION p0 VALUES LESS THAN (10) INDEX DIRECTORY = 'test'\n);",
        // invalid charsets
        "-- error ER_WRONG_VALUE_FOR_VAR\nset names ucs2;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset names ucs2 collate ucs2_bin;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset character_set_client= ucs2;",
        "-- error ER_WRONG_VALUE_FOR_VAR\nset character_set_client= concat('ucs', substr('2', 1));",
        // needs table/schema charset context
        "-- error ER_COLLATION_CHARSET_MISMATCH\nSELECT latin1_f,count(*) FROM t1 GROUP BY latin1_f COLLATE koi8r_general_ci;",
        "-- error ER_COLLATION_CHARSET_MISMATCH\nSELECT latin1_f COLLATE koi8r_general_ci  AS latin1_f_as FROM t1 ORDER BY latin1_f_as;",
        "-- error ER_COLLATION_CHARSET_MISMATCH\nSELECT latin1_f FROM t1 ORDER BY latin1_f COLLATE koi8r_general_ci;",
        "-- error ER_COLLATION_CHARSET_MISMATCH\nALTER TABLE t3 CONVERT TO CHARACTER SET DEFAULT COLLATE cp1251_general_cs;",
        // types in procedures
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 date, p2 date)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend|",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 integer, p2 float)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend|",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 integer, p2 char(1))\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend|",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 varchar(5), p2 char(1))\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend|",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 decimal, p2 decimal)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend|",
        "-- error ER_PARSE_ERROR\ncreate function f1(p1 double, p2 double)\n  returns int\nbegin\n  declare a int;\n  set a = (select count(*) from t1 limit p1, p2);\n  return a;\nend|",
    ];

}
