<?php declare(strict_types = 1);
/**
 * This file is part of the SqlFtw library (https://github.com/sqlftw)
 *
 * Copyright (c) 2017 Vlasta Neubauer (@paranoiq)
 *
 * For the full copyright and license information read the file 'license.md', distributed with this source code
 */

namespace SqlFtw\Platform\Features;

use SqlFtw\Sql\Dal\Cache\CacheIndexCommand;
use SqlFtw\Sql\Dal\Cache\LoadIndexIntoCacheCommand;
use SqlFtw\Sql\Dal\Flush\FlushCommand;
use SqlFtw\Sql\Dal\Flush\FlushTablesCommand;
use SqlFtw\Sql\Dal\Kill\KillCommand;
use SqlFtw\Sql\Dal\Plugin\InstallPluginCommand;
use SqlFtw\Sql\Dal\Plugin\UninstallPluginCommand;
use SqlFtw\Sql\Dal\Replication\ChangeMasterToCommand;
use SqlFtw\Sql\Dal\Replication\ResetMasterCommand;
use SqlFtw\Sql\Dal\Replication\ResetReplicaCommand;
use SqlFtw\Sql\Dal\Replication\ResetSlaveCommand;
use SqlFtw\Sql\Dal\Replication\StartReplicaCommand;
use SqlFtw\Sql\Dal\Replication\StartSlaveCommand;
use SqlFtw\Sql\Dal\Replication\StopReplicaCommand;
use SqlFtw\Sql\Dal\Replication\StopSlaveCommand;
use SqlFtw\Sql\Dal\Set\SetNamesCommand;
use SqlFtw\Sql\Dal\Set\SetVariablesCommand;
use SqlFtw\Sql\Dal\Show\ShowBinaryLogsCommand;
use SqlFtw\Sql\Dal\Show\ShowBinlogEventsCommand;
use SqlFtw\Sql\Dal\Show\ShowCharacterSetCommand;
use SqlFtw\Sql\Dal\Show\ShowCollationCommand;
use SqlFtw\Sql\Dal\Show\ShowColumnsCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateEventCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateFunctionCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateProcedureCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateSchemaCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateTableCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateTriggerCommand;
use SqlFtw\Sql\Dal\Show\ShowCreateViewCommand;
use SqlFtw\Sql\Dal\Show\ShowEngineCommand;
use SqlFtw\Sql\Dal\Show\ShowEnginesCommand;
use SqlFtw\Sql\Dal\Show\ShowEventsCommand;
use SqlFtw\Sql\Dal\Show\ShowFunctionStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowGrantsCommand;
use SqlFtw\Sql\Dal\Show\ShowIndexesCommand;
use SqlFtw\Sql\Dal\Show\ShowMasterStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowOpenTablesCommand;
use SqlFtw\Sql\Dal\Show\ShowProcedureStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowProcessListCommand;
use SqlFtw\Sql\Dal\Show\ShowProfileCommand;
use SqlFtw\Sql\Dal\Show\ShowReplicaStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowSchemasCommand;
use SqlFtw\Sql\Dal\Show\ShowSlaveStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowTablesCommand;
use SqlFtw\Sql\Dal\Show\ShowTableStatusCommand;
use SqlFtw\Sql\Dal\Show\ShowTriggersCommand;
use SqlFtw\Sql\Dal\Show\ShowVariablesCommand;
use SqlFtw\Sql\Dal\Table\AnalyzeTableDropHistogramCommand;
use SqlFtw\Sql\Dal\Table\AnalyzeTablesCommand;
use SqlFtw\Sql\Dal\Table\AnalyzeTableUpdateHistogramCommand;
use SqlFtw\Sql\Dal\Table\ChecksumTableCommand;
use SqlFtw\Sql\Dal\Table\OptimizeTableCommand;
use SqlFtw\Sql\Dal\Table\RepairTableCommand;
use SqlFtw\Sql\Dal\User\AlterUserCommand;
use SqlFtw\Sql\Dal\User\CreateUserCommand;
use SqlFtw\Sql\Dal\User\DropUserCommand;
use SqlFtw\Sql\Dal\User\GrantCommand;
use SqlFtw\Sql\Dal\User\RenameUserCommand;
use SqlFtw\Sql\Dal\User\RevokeAllCommand;
use SqlFtw\Sql\Dal\User\RevokeCommand;
use SqlFtw\Sql\Dal\User\RevokeProxyCommand;
use SqlFtw\Sql\Dal\User\RevokeRoleCommand;
use SqlFtw\Sql\Dal\User\SetPasswordCommand;
use SqlFtw\Sql\Dal\User\SetRoleCommand;
use SqlFtw\Sql\Ddl\Index\CreateIndexCommand;
use SqlFtw\Sql\Ddl\Index\DropIndexCommand;
use SqlFtw\Sql\Ddl\Schema\CreateSchemaCommand;
use SqlFtw\Sql\Ddl\Schema\DropSchemaCommand;
use SqlFtw\Sql\Ddl\Table\AlterTableCommand;
use SqlFtw\Sql\Ddl\Table\CreateTableCommand;
use SqlFtw\Sql\Ddl\Table\CreateTableLikeCommand;
use SqlFtw\Sql\Ddl\Table\DropTableCommand;
use SqlFtw\Sql\Ddl\Table\RenameTableCommand;
use SqlFtw\Sql\Ddl\Table\TruncateTableCommand;
use SqlFtw\Sql\Ddl\View\CreateViewCommand;
use SqlFtw\Sql\Ddl\View\DropViewCommand;
use SqlFtw\Sql\Dml\Call\CallCommand;
use SqlFtw\Sql\Dml\Delete\DeleteCommand;
use SqlFtw\Sql\Dml\DoCommand\DoCommand;
use SqlFtw\Sql\Dml\Insert\InsertCommand;
use SqlFtw\Sql\Dml\Insert\InsertSelectCommand;
use SqlFtw\Sql\Dml\Insert\InsertSetCommand;
use SqlFtw\Sql\Dml\Insert\InsertValuesCommand;
use SqlFtw\Sql\Dml\Insert\ReplaceSelectCommand;
use SqlFtw\Sql\Dml\Insert\ReplaceSetCommand;
use SqlFtw\Sql\Dml\Insert\ReplaceValuesCommand;
use SqlFtw\Sql\Dml\Query\ParenthesizedQueryExpression;
use SqlFtw\Sql\Dml\Query\SelectCommand;
use SqlFtw\Sql\Dml\Query\TableCommand;
use SqlFtw\Sql\Dml\Query\UnionExpression;
use SqlFtw\Sql\Dml\Query\ValuesCommand;
use SqlFtw\Sql\Dml\Transaction\CommitCommand;
use SqlFtw\Sql\Dml\Transaction\RollbackCommand;
use SqlFtw\Sql\Dml\Update\UpdateCommand;
use SqlFtw\Sql\Dml\Utility\DescribeTableCommand;
use SqlFtw\Sql\Dml\Utility\ExplainStatementCommand;
use SqlFtw\Sql\Expression\BaseType;
use SqlFtw\Sql\Expression\BuiltInFunction;
use SqlFtw\Sql\Expression\Operator;
use SqlFtw\Sql\Keyword;

class MysqlFeatures extends FeaturesList
{

    /** @var array<array{string, int, int}> */
    public $features = [
        // todo:
    ];

    /** @var array<array{string, int, int}> */
    public $reserved = [
        [Keyword::ACCESSIBLE, 50106, self::MAX],
        [Keyword::ADD, self::MIN, self::MAX],
        [Keyword::ADMIN, 80000, 80012],
        [Keyword::ALL, self::MIN, self::MAX],
        [Keyword::ALTER, self::MIN, self::MAX],
        [Keyword::ANALYZE, self::MIN, self::MAX],
        [Keyword::AND, self::MIN, self::MAX],
        [Keyword::ARRAY, 80017, 80019],
        [Keyword::AS, self::MIN, self::MAX],
        [Keyword::ASC, self::MIN, self::MAX],
        [Keyword::ASENSITIVE, 50000, self::MAX],
        [Keyword::BEFORE, self::MIN, self::MAX],
        [Keyword::BETWEEN, self::MIN, self::MAX],
        [Keyword::BIGINT, self::MIN, self::MAX],
        [Keyword::BINARY, self::MIN, self::MAX],
        [Keyword::BLOB, self::MIN, self::MAX],
        [Keyword::BOTH, self::MIN, self::MAX],
        [Keyword::BY, self::MIN, self::MAX],
        [Keyword::CALL, 50000, self::MAX],
        [Keyword::CASCADE, self::MIN, self::MAX],
        [Keyword::CASE, self::MIN, self::MAX],
        [Keyword::CHANGE, self::MIN, self::MAX],
        [Keyword::CHAR, self::MIN, self::MAX],
        [Keyword::CHARACTER, self::MIN, self::MAX],
        [Keyword::CHECK, self::MIN, self::MAX],
        [Keyword::COLLATE, self::MIN, self::MAX],
        [Keyword::COLUMN, self::MIN, self::MAX],
        [Keyword::CONDITION, 50000, self::MAX],
        [Keyword::CONSTRAINT, self::MIN, self::MAX],
        [Keyword::CONTINUE, 50000, self::MAX],
        [Keyword::CONVERT, self::MIN, self::MAX],
        [Keyword::CREATE, self::MIN, self::MAX],
        [Keyword::CROSS, self::MIN, self::MAX],
        [Keyword::CUBE, 80001, self::MAX],
        [Keyword::CUME_DIST, 80002, self::MAX],
        [Keyword::CURRENT_DATE, self::MIN, self::MAX],
        [Keyword::CURRENT_TIME, self::MIN, self::MAX],
        [Keyword::CURRENT_TIMESTAMP, self::MIN, self::MAX],
        [Keyword::CURRENT_USER, self::MIN, self::MAX],
        [Keyword::CURSOR, 50000, self::MAX],
        [Keyword::DATABASE, self::MIN, self::MAX],
        [Keyword::DATABASES, self::MIN, self::MAX],
        [Keyword::DAY_HOUR, self::MIN, self::MAX],
        [Keyword::DAY_MICROSECOND, self::MIN, self::MAX],
        [Keyword::DAY_MINUTE, self::MIN, self::MAX],
        [Keyword::DAY_SECOND, self::MIN, self::MAX],
        [Keyword::DEC, self::MIN, self::MAX],
        [Keyword::DECIMAL, self::MIN, self::MAX],
        [Keyword::DECLARE, 50000, self::MAX],
        [Keyword::DEFAULT, self::MIN, self::MAX],
        [Keyword::DELAYED, self::MIN, self::MAX],
        [Keyword::DELETE, self::MIN, self::MAX],
        [Keyword::DENSE_RANK, 80002, self::MAX],
        [Keyword::DESC, self::MIN, self::MAX],
        [Keyword::DESCRIBE, self::MIN, self::MAX],
        [Keyword::DETERMINISTIC, 50000, self::MAX],
        [Keyword::DISTINCT, self::MIN, self::MAX],
        [Keyword::DISTINCTROW, self::MIN, self::MAX],
        [Keyword::DIV, self::MIN, self::MAX],
        [Keyword::DOUBLE, self::MIN, self::MAX],
        [Keyword::DROP, self::MIN, self::MAX],
        [Keyword::DUAL, self::MIN, self::MAX],
        [Keyword::EACH, 50000, self::MAX],
        [Keyword::ELSE, self::MIN, self::MAX],
        [Keyword::ELSEIF, 50000, self::MAX],
        [Keyword::EMPTY, 80004, self::MAX],
        [Keyword::ENCLOSED, self::MIN, self::MAX],
        [Keyword::ESCAPED, self::MIN, self::MAX],
        [Keyword::EXISTS, self::MIN, self::MAX],
        [Keyword::EXIT, 50000, self::MAX],
        [Keyword::EXPLAIN, self::MIN, self::MAX],
        [Keyword::FALSE, self::MIN, self::MAX],
        [Keyword::FETCH, 50000, self::MAX],
        [Keyword::FIRST_VALUE, 80002, self::MAX],
        [Keyword::FLOAT, self::MIN, self::MAX],
        [Keyword::FLOAT4, self::MIN, self::MAX],
        [Keyword::FLOAT8, self::MIN, self::MAX],
        [Keyword::FOR, self::MIN, self::MAX],
        [Keyword::FORCE, self::MIN, self::MAX],
        [Keyword::FOREIGN, self::MIN, self::MAX],
        [Keyword::FROM, self::MIN, self::MAX],
        [Keyword::FULLTEXT, self::MIN, self::MAX],
        [Keyword::FUNCTION, 80001, self::MAX],
        [Keyword::GENERAL, 50503, 50508],
        [Keyword::GENERAL, 50600, 50601],
        [Keyword::GENERATED, 50706, self::MAX],
        [Keyword::GET, 50604, self::MAX],
        [Keyword::GET_MASTER_PUBLIC_KEY, 80004, 80011],
        [Keyword::GRANT, self::MIN, self::MAX],
        [Keyword::GROUP, self::MIN, self::MAX],
        [Keyword::GROUPING, 80001, self::MAX],
        [Keyword::GROUPS, 80002, self::MAX],
        [Keyword::HAVING, self::MIN, self::MAX],
        [Keyword::HIGH_PRIORITY, self::MIN, self::MAX],
        [Keyword::HOUR_MICROSECOND, self::MIN, self::MAX],
        [Keyword::HOUR_MINUTE, self::MIN, self::MAX],
        [Keyword::HOUR_SECOND, self::MIN, self::MAX],
        [Keyword::IF, self::MIN, self::MAX],
        [Keyword::IGNORE, self::MIN, self::MAX],
        [Keyword::IGNORE_SERVER_IDS, 50500, 50508],
        [Keyword::IGNORE_SERVER_IDS, 50600, 50601],
        [Keyword::IN, self::MIN, self::MAX],
        [Keyword::INDEX, self::MIN, self::MAX],
        [Keyword::INFILE, self::MIN, self::MAX],
        [Keyword::INNER, self::MIN, self::MAX],
        [Keyword::INOUT, 50000, self::MAX],
        [Keyword::INSENSITIVE, 50000, self::MAX],
        [Keyword::INSERT, self::MIN, self::MAX],
        [Keyword::INT, self::MIN, self::MAX],
        [Keyword::INT1, self::MIN, self::MAX],
        [Keyword::INT2, self::MIN, self::MAX],
        [Keyword::INT3, self::MIN, self::MAX],
        [Keyword::INT4, self::MIN, self::MAX],
        [Keyword::INT8, self::MIN, self::MAX],
        [Keyword::INTEGER, self::MIN, self::MAX],
        [Keyword::INTERVAL, self::MIN, self::MAX],
        [Keyword::INTERSECT, 80031, self::MAX],
        [Keyword::INTO, self::MIN, self::MAX],
        [Keyword::IO_AFTER_GTIDS, 50605, self::MAX],
        [Keyword::IO_BEFORE_GTIDS, 50605, self::MAX],
        [Keyword::IS, self::MIN, self::MAX],
        [Keyword::ITERATE, 50000, self::MAX],
        [Keyword::JOIN, self::MIN, self::MAX],
        [Keyword::JSON_TABLE, 80004, self::MAX],
        [Keyword::KEY, self::MIN, self::MAX],
        [Keyword::KEYS, self::MIN, self::MAX],
        [Keyword::KILL, self::MIN, self::MAX],
        [Keyword::LAG, 80002, self::MAX],
        [Keyword::LAST_VALUE, 80002, self::MAX],
        [Keyword::LATERAL, 80014, self::MAX],
        [Keyword::LEAD, 80002, self::MAX],
        [Keyword::LEADING, self::MIN, self::MAX],
        [Keyword::LEAVE, 50000, self::MAX],
        [Keyword::LEFT, self::MIN, self::MAX],
        [Keyword::LIKE, self::MIN, self::MAX],
        [Keyword::LIMIT, self::MIN, self::MAX],
        [Keyword::LINEAR, 50100, self::MAX],
        [Keyword::LINES, self::MIN, self::MAX],
        [Keyword::LOAD, self::MIN, self::MAX],
        [Keyword::LOCALTIME, self::MIN, self::MAX],
        [Keyword::LOCALTIMESTAMP, self::MIN, self::MAX],
        [Keyword::LOCK, self::MIN, self::MAX],
        [Keyword::LONG, self::MIN, self::MAX],
        [Keyword::LONGBLOB, self::MIN, self::MAX],
        [Keyword::LONGTEXT, self::MIN, self::MAX],
        [Keyword::LOOP, 50000, self::MAX],
        [Keyword::LOW_PRIORITY, self::MIN, self::MAX],
        [Keyword::MASTER_BIND, 50601, self::MAX],
        [Keyword::MASTER_HEARTBEAT_PERIOD, 50500, 50508],
        [Keyword::MASTER_HEARTBEAT_PERIOD, 50600, 50601],
        [Keyword::MASTER_SSL_VERIFY_SERVER_CERT, 50118, self::MAX],
        [Keyword::MATCH, self::MIN, self::MAX],
        [Keyword::MEDIUMBLOB, self::MIN, self::MAX],
        [Keyword::MEDIUMINT, self::MIN, self::MAX],
        [Keyword::MEDIUMTEXT, self::MIN, self::MAX],
        [Keyword::MEMBER, 80017, 80019],
        [Keyword::MIDDLEINT, self::MIN, self::MAX],
        [Keyword::MINUTE_MICROSECOND, self::MIN, self::MAX],
        [Keyword::MINUTE_SECOND, self::MIN, self::MAX],
        [Keyword::MOD, self::MIN, self::MAX],
        [Keyword::MODIFIES, 50000, self::MAX],
        [Keyword::NATURAL, self::MIN, self::MAX],
        [Keyword::NO_WRITE_TO_BINLOG, self::MIN, self::MAX],
        [Keyword::NOT, self::MIN, self::MAX],
        [Keyword::NTH_VALUE, 80002, self::MAX],
        [Keyword::NTILE, 80002, self::MAX],
        [Keyword::NULL, self::MIN, self::MAX],
        [Keyword::NUMERIC, self::MIN, self::MAX],
        [Keyword::OF, 80001, self::MAX],
        [Keyword::ON, self::MIN, self::MAX],
        [Keyword::OPTIMIZE, self::MIN, self::MAX],
        [Keyword::OPTIMIZER_COSTS, 50705, self::MAX],
        [Keyword::OPTION, self::MIN, self::MAX],
        [Keyword::OPTIONALLY, self::MIN, self::MAX],
        [Keyword::OR, self::MIN, self::MAX],
        [Keyword::ORDER, self::MIN, self::MAX],
        [Keyword::OUT, 50000, self::MAX],
        [Keyword::OUTER, self::MIN, self::MAX],
        [Keyword::OUTFILE, self::MIN, self::MAX],
        [Keyword::OVER, 80002, self::MAX],
        [Keyword::PARSE_GCOL_EXPR, 50706, 50708],
        [Keyword::PARTITION, 50100, self::MAX],
        [Keyword::PERCENT_RANK, 80002, self::MAX],
        [Keyword::PERSIST, 80000, 80016],
        [Keyword::PERSIST_ONLY, 80002, 80016],
        [Keyword::PRECISION, self::MIN, self::MAX],
        [Keyword::PRIMARY, self::MIN, self::MAX],
        [Keyword::PROCEDURE, self::MIN, self::MAX],
        [Keyword::PURGE, self::MIN, self::MAX],
        [Keyword::RANGE, 50100, self::MAX],
        [Keyword::RANK, 80002, self::MAX],
        [Keyword::READ, self::MIN, self::MAX],
        [Keyword::READ_ONLY, 50106, 50124],
        [Keyword::READ_WRITE, 50106, self::MAX],
        [Keyword::READS, 50000, self::MAX],
        [Keyword::REAL, self::MIN, self::MAX],
        [Keyword::RECURSIVE, 80001, self::MAX],
        [Keyword::REFERENCES, self::MIN, self::MAX],
        [Keyword::REGEXP, self::MIN, self::MAX],
        [Keyword::RELEASE, 50000, self::MAX],
        [Keyword::RENAME, self::MIN, self::MAX],
        [Keyword::REPEAT, 50000, self::MAX],
        [Keyword::REPLACE, self::MIN, self::MAX],
        [Keyword::REQUIRE, self::MIN, self::MAX],
        [Keyword::RESIGNAL, 50500, self::MAX],
        [Keyword::RESTRICT, self::MIN, self::MAX],
        [Keyword::RETURN, 50000, self::MAX],
        [Keyword::REVOKE, self::MIN, self::MAX],
        [Keyword::RIGHT, self::MIN, self::MAX],
        [Keyword::RLIKE, self::MIN, self::MAX],
        [Keyword::ROLE, 80000, 80001],
        [Keyword::ROW, 80002, self::MAX],
        [Keyword::ROW_NUMBER, 80002, self::MAX],
        [Keyword::ROWS, 80002, self::MAX],
        [Keyword::SECOND_MICROSECOND, self::MIN, self::MAX],
        [Keyword::SECOND_MICROSECOND, 80000, self::MAX],
        [Keyword::SELECT, self::MIN, self::MAX],
        [Keyword::SENSITIVE, 50000, self::MAX],
        [Keyword::SEPARATOR, self::MIN, self::MAX],
        [Keyword::SET, self::MIN, self::MAX],
        [Keyword::SHOW, self::MIN, self::MAX],
        [Keyword::SCHEMA, 50000, self::MAX],
        [Keyword::SCHEMAS, 50000, self::MAX],
        [Keyword::SIGNAL, 50500, self::MAX],
        [Keyword::SLOW, 50503, 50508],
        [Keyword::SLOW, 50600, 50601],
        [Keyword::SMALLINT, self::MIN, self::MAX],
        [Keyword::SPATIAL, self::MIN, self::MAX],
        [Keyword::SPECIFIC, 50000, self::MAX],
        [Keyword::SQL, 50000, self::MAX],
        [Keyword::SQL_AFTER_GTIDS, 50605, 50606],
        [Keyword::SQL_BEFORE_GTIDS, 50605, 50606],
        [Keyword::SQL_BIG_RESULT, self::MIN, self::MAX],
        [Keyword::SQL_CALC_FOUND_ROWS, self::MIN, self::MAX],
        [Keyword::SQL_SMALL_RESULT, self::MIN, self::MAX],
        [Keyword::SQLEXCEPTION, 50000, self::MAX],
        [Keyword::SQLSTATE, 50000, self::MAX],
        [Keyword::SQLWARNING, 50000, self::MAX],
        [Keyword::SSL, self::MIN, self::MAX],
        [Keyword::STARTING, self::MIN, self::MAX],
        [Keyword::STORED, 50706, self::MAX],
        [Keyword::STRAIGHT_JOIN, self::MIN, self::MAX],
        [Keyword::SYSTEM, 80003, self::MAX],
        [Keyword::TABLE, self::MIN, self::MAX],
        [Keyword::TERMINATED, self::MIN, self::MAX],
        [Keyword::THEN, self::MIN, self::MAX],
        [Keyword::TINYBLOB, self::MIN, self::MAX],
        [Keyword::TINYINT, self::MIN, self::MAX],
        [Keyword::TINYTEXT, self::MIN, self::MAX],
        [Keyword::TO, self::MIN, self::MAX],
        [Keyword::TRAILING, self::MIN, self::MAX],
        [Keyword::TRIGGER, 50000, self::MAX],
        [Keyword::TRUE, self::MIN, self::MAX],
        [Keyword::UNDO, 50000, self::MAX],
        [Keyword::UNION, self::MIN, self::MAX],
        [Keyword::UNIQUE, self::MIN, self::MAX],
        [Keyword::UNLOCK, self::MIN, self::MAX],
        [Keyword::UNSIGNED, self::MIN, self::MAX],
        [Keyword::UPDATE, self::MIN, self::MAX],
        [Keyword::UPGRADE, 50107, 50112],
        [Keyword::USAGE, self::MIN, self::MAX],
        [Keyword::USE, self::MIN, self::MAX],
        [Keyword::USING, self::MIN, self::MAX],
        [Keyword::UTC_DATE, self::MIN, self::MAX],
        [Keyword::UTC_TIME, self::MIN, self::MAX],
        [Keyword::UTC_TIMESTAMP, self::MIN, self::MAX],
        [Keyword::VALUES, self::MIN, self::MAX],
        [Keyword::VARBINARY, self::MIN, self::MAX],
        [Keyword::VARCHAR, self::MIN, self::MAX],
        [Keyword::VARCHARACTER, self::MIN, self::MAX],
        [Keyword::VARYING, self::MIN, self::MAX],
        [Keyword::VIRTUAL, 50706, self::MAX],
        [Keyword::WHEN, self::MIN, self::MAX],
        [Keyword::WHERE, self::MIN, self::MAX],
        [Keyword::WHILE, 50000, self::MAX],
        [Keyword::WINDOW, 80002, self::MAX],
        [Keyword::WITH, self::MIN, self::MAX],
        [Keyword::WRITE, self::MIN, self::MAX],
        [Keyword::XOR, self::MIN, self::MAX],
        [Keyword::YEAR_MONTH, self::MIN, self::MAX],
        [Keyword::ZEROFILL, self::MIN, self::MAX],
    ];

    /** @var array<array{string, int, int}> */
    public $nonReserved = [
        [Keyword::ACCOUNT, 50706, self::MAX],
        [Keyword::ACTION, self::MIN, self::MAX],
        [Keyword::ACTIVE, 80014, self::MAX],
        [Keyword::ADMIN, 80012, self::MAX],
        [Keyword::AFTER, self::MIN, self::MAX],
        [Keyword::AGAINST, self::MIN, self::MAX],
        [Keyword::AGGREGATE, self::MIN, self::MAX],
        [Keyword::ALGORITHM, 50000, self::MAX],
        [Keyword::ALWAYS, 50706, self::MAX],
        [Keyword::ANALYSE, 50600, 80001],
        [Keyword::ANY, self::MIN, self::MAX],
        [Keyword::ARRAY, 80019, self::MAX],
        [Keyword::ASCII, self::MIN, self::MAX],
        [Keyword::ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS, 80023, self::MAX], // not listed
        [Keyword::AT, 50106, self::MAX],
        [Keyword::ATTRIBUTE, 80021, self::MAX],
        [Keyword::AUTHENTICATION, 80027, self::MAX],
        [Keyword::AUTHORS, 50100, 50608],
        [Keyword::AUTO_INCREMENT, self::MIN, self::MAX],
        [Keyword::AUTOEXTEND_SIZE, 50106, self::MAX],
        [Keyword::AVG, self::MIN, self::MAX],
        [Keyword::AVG_ROW_LENGTH, self::MIN, self::MAX],
        [Keyword::BACKUP, self::MIN, self::MAX],
        [Keyword::BDB, self::MIN, 50112],
        [Keyword::BEGIN, self::MIN, self::MAX],
        [Keyword::BERKELEYDB, self::MIN, 50112],
        [Keyword::BINLOG, self::MIN, self::MAX],
        [Keyword::BIT, self::MIN, self::MAX],
        [Keyword::BLOCK, 50000, self::MAX],
        [Keyword::BOOL, self::MIN, self::MAX],
        [Keyword::BOOLEAN, self::MIN, self::MAX],
        [Keyword::BTREE, self::MIN, self::MAX],
        [Keyword::BUCKETS, 80002, self::MAX],
        [Keyword::BYTE, self::MIN, self::MAX],
        [Keyword::CACHE, self::MIN, self::MAX],
        [Keyword::CASCADED, 50000, self::MAX],
        [Keyword::CATALOG_NAME, 50500, self::MAX],
        [Keyword::CHAIN, 50000, self::MAX],
        [Keyword::CHALLENGE_RESPONSE, 80027, self::MAX],
        [Keyword::CHANGED, self::MIN, self::MAX],
        [Keyword::CHANNEL, 50706, self::MAX],
        [Keyword::CHARSET, self::MIN, self::MAX],
        [Keyword::CHECKSUM, self::MIN, self::MAX],
        [Keyword::CIPHER, self::MIN, self::MAX],
        [Keyword::CLASS_ORIGIN, 50500, self::MAX],
        [Keyword::CLIENT, self::MIN, self::MAX],
        [Keyword::CLONE, 80003, self::MAX],
        [Keyword::CLOSE, self::MIN, self::MAX],
        [Keyword::COALESCE, 50100, self::MAX],
        [Keyword::CODE, 50000, self::MAX],
        [Keyword::COLLATION, self::MIN, self::MAX],
        [Keyword::COLUMN_FORMAT, 50606, self::MAX],
        [Keyword::COLUMN_NAME, 50500, self::MAX],
        [Keyword::COLUMNS, self::MIN, self::MAX],
        [Keyword::COMMENT, self::MIN, self::MAX],
        [Keyword::COMMIT, self::MIN, self::MAX],
        [Keyword::COMMITTED, self::MIN, self::MAX],
        [Keyword::COMPACT, 50000, self::MAX],
        [Keyword::COMPLETION, 50106, self::MAX],
        [Keyword::COMPONENT, 80000, self::MAX],
        [Keyword::COMPRESSED, self::MIN, self::MAX],
        [Keyword::COMPRESSION, 50708, self::MAX],
        [Keyword::CONCURRENT, self::MIN, self::MAX],
        [Keyword::CONNECTION, 50000, self::MAX],
        [Keyword::CONSISTENT, self::MIN, self::MAX],
        [Keyword::CONSTRAINT_CATALOG, 50500, self::MAX],
        [Keyword::CONSTRAINT_NAME, 50500, self::MAX],
        [Keyword::CONSTRAINT_SCHEMA, 50500, self::MAX],
        [Keyword::CONTAINS, 50000, self::MAX],
        [Keyword::CONTEXT, 50000, self::MAX],
        [Keyword::CONTRIBUTORS, 50112, 50608],
        [Keyword::CPU, 50000, self::MAX],
        [Keyword::CUBE, self::MIN, 80001],
        [Keyword::CURRENT, 50604, self::MAX],
        [Keyword::CURSOR_NAME, 50500, self::MAX],
        [Keyword::DATA, self::MIN, self::MAX],
        [Keyword::DATAFILE, 50106, self::MAX],
        [Keyword::DATE, self::MIN, self::MAX],
        [Keyword::DATETIME, self::MIN, self::MAX],
        [Keyword::DAY, self::MIN, self::MAX],
        [Keyword::DEALLOCATE, self::MIN, self::MAX],
        [Keyword::DEFAULT_AUTH, 50604, self::MAX],
        [Keyword::DEFINER, 50000, self::MAX],
        [Keyword::DEFINITION, 80004, self::MAX],
        [Keyword::DELAY_KEY_WRITE, self::MIN, self::MAX],
        [Keyword::DES_KEY_FILE, self::MIN, self::MAX],
        [Keyword::DESCRIPTION, 80004, self::MAX],
        [Keyword::DES_KEY_FILE, 80000, 80003],
        [Keyword::DIAGNOSTICS, 50604, self::MAX],
        [Keyword::DIRECTORY, self::MIN, self::MAX],
        [Keyword::DISABLE, self::MIN, self::MAX],
        [Keyword::DISCARD, self::MIN, self::MAX],
        [Keyword::DISK, 50106, self::MAX],
        [Keyword::DO, self::MIN, self::MAX],
        [Keyword::DUMPFILE, self::MIN, self::MAX],
        [Keyword::DUPLICATE, self::MIN, self::MAX],
        [Keyword::DYNAMIC, self::MIN, self::MAX],
        [Keyword::ENABLE, self::MIN, self::MAX],
        [Keyword::ENCRYPTION, 50711, self::MAX],
        [Keyword::END, self::MIN, self::MAX],
        [Keyword::ENDS, 50106, self::MAX],
        [Keyword::ENFORCED, 80016, self::MAX],
        [Keyword::ENGINE, self::MIN, self::MAX],
        [Keyword::ENGINE_ATTRIBUTE, 80021, self::MAX],
        [Keyword::ENGINES, self::MIN, self::MAX],
        [Keyword::ENUM, self::MIN, self::MAX],
        [Keyword::ERROR, 50500, self::MAX],
        [Keyword::ERRORS, self::MIN, self::MAX],
        [Keyword::ESCAPE, self::MIN, self::MAX],
        [Keyword::EVENT, self::MIN, self::MAX],
        [Keyword::EVENTS, 50106, self::MAX],
        [Keyword::EVERY, 50106, self::MAX],
        [Keyword::EXCEPT, 80000, self::MAX],
        [Keyword::EXCHANGE, 50600, self::MAX],
        [Keyword::EXCLUDE, 80002, self::MAX],
        [Keyword::EXECUTE, self::MIN, self::MAX],
        [Keyword::EXPANSION, self::MIN, self::MAX],
        [Keyword::EXPIRE, 50606, self::MAX],
        [Keyword::EXPORT, 50606, self::MAX],
        [Keyword::EXTENDED, self::MIN, self::MAX],
        [Keyword::EXTENT_SIZE, 50106, self::MAX],
        [Keyword::FACTOR, 80027, self::MAX],
        [Keyword::FAILED_LOGIN_ATTEMPTS, 80019, self::MAX],
        [Keyword::FAST, self::MIN, self::MAX],
        [Keyword::FAULTS, 50000, self::MAX],
        [Keyword::FIELDS, self::MIN, self::MAX],
        [Keyword::FILE, self::MIN, self::MAX],
        [Keyword::FILE_BLOCK_SIZE, 50706, self::MAX],
        [Keyword::FILTER, 50703, self::MAX],
        [Keyword::FINISH, 80027, self::MAX],
        [Keyword::FIRST, self::MIN, self::MAX],
        [Keyword::FIXED, self::MIN, self::MAX],
        [Keyword::FLUSH, self::MIN, self::MAX],
        [Keyword::FOLLOWING, 80002, self::MAX],
        [Keyword::FOLLOWS, 50702, self::MAX],
        [Keyword::FORMAT, 50605, self::MAX],
        [Keyword::FOUND, 50000, self::MAX],
        [Keyword::FRAC_SECOND, 50000, 50503],
        [Keyword::FULL, self::MIN, self::MAX],
        [Keyword::FUNCTION, self::MIN, 80001],
        [Keyword::GENERAL, 50508, self::MAX],
        [Keyword::GENERAL, 50601, self::MAX],
        [Keyword::GEOMCOLLECTION, 80011, self::MAX],
        [Keyword::GEOMETRY, self::MIN, self::MAX],
        [Keyword::GEOMETRYCOLLECTION, self::MIN, self::MAX],
        [Keyword::GET_FORMAT, self::MIN, self::MAX],
        [Keyword::GET_MASTER_PUBLIC_KEY, 80011, self::MAX],
        [Keyword::GET_SOURCE_PUBLIC_KEY, 80023, self::MAX],
        [Keyword::GLOBAL, self::MIN, self::MAX],
        [Keyword::GOTO, self::MIN, 50111],
        [Keyword::GRANTS, self::MIN, self::MAX],
        [Keyword::GROUP_REPLICATION, 50706, self::MAX],
        [Keyword::GTID_ONLY, 80027, self::MAX],
        [Keyword::HANDLER, self::MIN, self::MAX],
        [Keyword::HASH, self::MIN, self::MAX],
        [Keyword::HELP, self::MIN, self::MAX],
        [Keyword::HISTOGRAM, 80002, self::MAX],
        [Keyword::HISTORY, 80003, self::MAX],
        [Keyword::HOST, 50115, self::MAX],
        [Keyword::HOSTS, self::MIN, self::MAX],
        [Keyword::HOUR, self::MIN, self::MAX],
        [Keyword::IDENTIFIED, self::MIN, self::MAX],
        [Keyword::IGNORE_SERVER_IDS, 50500, self::MAX],
        [Keyword::IGNORE_SERVER_IDS, 50508, self::MAX],
        [Keyword::IGNORE_SERVER_IDS, 50601, self::MAX],
        [Keyword::IMPORT, self::MIN, self::MAX],
        [Keyword::INACTIVE, 80014, self::MAX],
        [Keyword::INDEXES, self::MIN, self::MAX],
        [Keyword::INITIAL, 80027, self::MAX],
        [Keyword::INITIAL_SIZE, 50106, self::MAX],
        [Keyword::INITIATE, 80027, self::MAX],
        [Keyword::INNOBASE, self::MIN, 50503],
        [Keyword::INNODB, self::MIN, self::MAX], // removed in 50503, but used e.g. in ROTATE INNODB MASTER KEY
        [Keyword::INSERT_METHOD, self::MIN, self::MAX],
        [Keyword::INSTALL, 50100, self::MAX],
        [Keyword::INSTANCE, 50711, self::MAX],
        [Keyword::INVISIBLE, 80000, self::MAX],
        [Keyword::INVOKER, 50000, self::MAX],
        [Keyword::IO, 50000, self::MAX],
        [Keyword::IO_THREAD, self::MIN, self::MAX],
        [Keyword::IPC, 50000, self::MAX],
        [Keyword::ISOLATION, self::MIN, self::MAX],
        [Keyword::ISSUER, self::MIN, self::MAX],
        [Keyword::JSON, 50708, self::MAX],
        [Keyword::JSON_VALUE, 80021, self::MAX],
        [Keyword::KEY_BLOCK_SIZE, 50111, self::MAX],
        [Keyword::KEYRING, 80024, self::MAX],
        [Keyword::LABEL, self::MIN, 50111],
        [Keyword::LANGUAGE, 50000, self::MAX],
        [Keyword::LAST, self::MIN, self::MAX],
        [Keyword::LEAVES, self::MIN, self::MAX],
        [Keyword::LESS, 50100, self::MAX],
        [Keyword::LEVEL, self::MIN, self::MAX],
        [Keyword::LINESTRING, self::MIN, self::MAX],
        [Keyword::LIST, 50100, self::MAX],
        [Keyword::LOCAL, self::MIN, self::MAX],
        [Keyword::LOCKED, 80002, self::MAX],
        [Keyword::LOCKS, self::MIN, self::MAX],
        [Keyword::LOGFILE, 50106, self::MAX],
        [Keyword::LOGS, self::MIN, self::MAX],
        [Keyword::MASTER, self::MIN, self::MAX],
        [Keyword::MASTER_AUTO_POSITION, 50605, self::MAX],
        [Keyword::MASTER_COMPRESSION_ALGORITHMS, 80018, self::MAX],
        [Keyword::MASTER_CONNECT_RETRY, self::MIN, self::MAX],
        [Keyword::MASTER_DELAY, 50600, self::MAX],
        [Keyword::MASTER_HEARTBEAT_PERIOD, 50508, 50599],
        [Keyword::MASTER_HEARTBEAT_PERIOD, 50601, self::MAX],
        [Keyword::MASTER_HOST, self::MIN, self::MAX],
        [Keyword::MASTER_LOG_FILE, self::MIN, self::MAX],
        [Keyword::MASTER_LOG_POS, self::MIN, self::MAX],
        [Keyword::MASTER_PASSWORD, self::MIN, self::MAX],
        [Keyword::MASTER_PORT, self::MIN, self::MAX],
        [Keyword::MASTER_PUBLIC_KEY_PATH, 80004, self::MAX],
        [Keyword::MASTER_RETRY_COUNT, 50601, self::MAX],
        [Keyword::MASTER_SERVER_ID, self::MIN, 80023],
        [Keyword::MASTER_SSL, self::MIN, self::MAX],
        [Keyword::MASTER_SSL_CA, self::MIN, self::MAX],
        [Keyword::MASTER_SSL_CAPATH, self::MIN, self::MAX],
        [Keyword::MASTER_SSL_CERT, self::MIN, self::MAX],
        [Keyword::MASTER_SSL_CIPHER, self::MIN, self::MAX],
        [Keyword::MASTER_SSL_CRL, 50603, self::MAX],
        [Keyword::MASTER_SSL_CRLPATH, 50603, self::MAX],
        [Keyword::MASTER_SSL_KEY, self::MIN, self::MAX],
        [Keyword::MASTER_TLS_CIPHERSUITES, 80019, self::MAX],
        [Keyword::MASTER_TLS_VERSION, 50710, self::MAX],
        [Keyword::MASTER_USER, self::MIN, self::MAX],
        [Keyword::MASTER_ZSTD_COMPRESSION_LEVEL, 80018, self::MAX],
        [Keyword::MAX_CONNECTIONS_PER_HOUR, self::MIN, self::MAX],
        [Keyword::MAX_QUERIES_PER_HOUR, self::MIN, self::MAX],
        [Keyword::MAX_ROWS, self::MIN, self::MAX],
        [Keyword::MAX_SIZE, 50106, self::MAX],
        [Keyword::MAX_STATEMENT_TIME, 50704, 50708],
        [Keyword::MAX_UPDATES_PER_HOUR, self::MIN, self::MAX],
        [Keyword::MAX_USER_CONNECTIONS, 50000, self::MAX],
        [Keyword::MAXVALUE, 50100, self::MAX],
        [Keyword::MEDIUM, self::MIN, self::MAX],
        [Keyword::MEMBER, 80019, self::MAX],
        [Keyword::MEMORY, 50000, self::MAX],
        [Keyword::MERGE, 50000, self::MAX],
        [Keyword::MESSAGE_TEXT, 50500, self::MAX],
        [Keyword::MICROSECOND, self::MIN, self::MAX],
        [Keyword::MIGRATE, 50000, self::MAX],
        [Keyword::MIN_ROWS, self::MIN, self::MAX],
        [Keyword::MINUTE, self::MIN, self::MAX],
        [Keyword::MODE, self::MIN, self::MAX],
        [Keyword::MODIFY, self::MIN, self::MAX],
        [Keyword::MONTH, self::MIN, self::MAX],
        [Keyword::MULTILINESTRING, self::MIN, self::MAX],
        [Keyword::MULTIPOINT, self::MIN, self::MAX],
        [Keyword::MULTIPOLYGON, self::MIN, self::MAX],
        [Keyword::MUTEX, 50000, self::MAX],
        [Keyword::MYSQL_ERRNO, 50500, self::MAX],
        [Keyword::NAME, 50000, self::MAX],
        [Keyword::NAMES, self::MIN, self::MAX],
        [Keyword::NATIONAL, self::MIN, self::MAX],
        [Keyword::NDB, self::MIN, self::MAX],
        [Keyword::NDBCLUSTER, self::MIN, self::MAX],
        [Keyword::NESTED, 80004, self::MAX],
        [Keyword::NETWORK_NAMESPACE, 80016, self::MAX],
        [Keyword::NEVER, 50704, self::MAX],
        [Keyword::NEW, self::MIN, self::MAX],
        [Keyword::NEXT, self::MIN, self::MAX],
        [Keyword::NCHAR, self::MIN, self::MAX],
        [Keyword::NO, self::MIN, self::MAX],
        [Keyword::NO_WAIT, 50106, self::MAX],
        [Keyword::NODEGROUP, 50100, self::MAX],
        [Keyword::NONBLOCKING, 50706, self::MAX],
        [Keyword::NONE, self::MIN, self::MAX],
        [Keyword::NOWAIT, 80001, self::MAX],
        [Keyword::NULLS, 80002, self::MAX],
        [Keyword::NUMBER, 50604, self::MAX],
        [Keyword::NVARCHAR, self::MIN, self::MAX],
        [Keyword::OFF, 80020, self::MAX],
        [Keyword::OFFSET, self::MIN, self::MAX],
        [Keyword::OJ, 80016, self::MAX],
        [Keyword::OLD, 80014, self::MAX],
        [Keyword::OLD_PASSWORD, self::MIN, 50705],
        [Keyword::ONE, 50000, self::MAX],
        [Keyword::ONE_SHOT, self::MIN, 50605],
        [Keyword::ONLINE, 50500, self::MAX], // not listed, but mentioned in NDB docs since 5.5
        [Keyword::ONLY, 50605, self::MAX],
        [Keyword::OPEN, self::MIN, self::MAX],
        [Keyword::OPTIONAL, 80013, self::MAX],
        [Keyword::OPTIONS, 50115, self::MAX],
        [Keyword::ORDINALITY, 80004, self::MAX],
        [Keyword::ORGANIZATION, 80004, self::MAX],
        [Keyword::OTHERS, 80002, self::MAX],
        [Keyword::OWNER, 50115, self::MAX],
        [Keyword::PACK_KEYS, self::MIN, self::MAX],
        [Keyword::PAGE, 50000, self::MAX],
        [Keyword::PAGE_CHECKSUM, 50124, 50138],
        [Keyword::PARSE_GCOL_EXPR, 50708, self::MAX],
        [Keyword::PARSER, 50100, self::MAX],
        [Keyword::PARTIAL, self::MIN, self::MAX],
        [Keyword::PARTITIONING, 50119, self::MAX],
        [Keyword::PARTITIONS, 50100, self::MAX],
        [Keyword::PASSWORD, self::MIN, self::MAX],
        [Keyword::PASSWORD_LOCK_TIME, 80019, self::MAX],
        [Keyword::PATH, 80004, self::MAX],
        [Keyword::PERSIST, 80016, self::MAX],
        [Keyword::PERSIST_ONLY, 80016, self::MAX],
        [Keyword::PHASE, 50000, self::MAX],
        [Keyword::PLUGIN, 50100, self::MAX],
        [Keyword::PLUGIN_DIR, 50604, self::MAX],
        [Keyword::PLUGINS, 50119, self::MAX],
        [Keyword::POINT, self::MIN, self::MAX],
        [Keyword::POLYGON, self::MIN, self::MAX],
        [Keyword::PORT, 50115, self::MAX],
        [Keyword::PRECEDES, 50702, self::MAX],
        [Keyword::PRECEDING, 80002, self::MAX],
        [Keyword::PREPARE, self::MIN, self::MAX],
        [Keyword::PRESERVE, 50106, self::MAX],
        [Keyword::PREV, self::MIN, self::MAX],
        [Keyword::PRIVILEGE_CHECKS_USER, 80018, self::MAX],
        [Keyword::PRIVILEGES, self::MIN, self::MAX],
        [Keyword::PROCESS, 80011, self::MAX],
        [Keyword::PROCESSLIST, self::MIN, self::MAX],
        [Keyword::PROFILE, 50000, self::MAX],
        [Keyword::PROFILES, 50000, self::MAX],
        [Keyword::PROXY, 50507, self::MAX],
        [Keyword::PROXY, 50601, self::MAX],
        [Keyword::QUARTER, 50000, self::MAX],
        [Keyword::QUERY, self::MIN, self::MAX],
        [Keyword::QUICK, self::MIN, self::MAX],
        [Keyword::RAID_CHUNKS, self::MIN, 50107],
        [Keyword::RAID_CHUNKSIZE, self::MIN, 50107],
        [Keyword::RAID_TYPE, self::MIN, 50107],
        [Keyword::RAID0, self::MIN, 50107],
        [Keyword::RANDOM, 80018, self::MAX],
        [Keyword::READ_ONLY, 50124, self::MAX],
        [Keyword::REBUILD, 50106, self::MAX],
        [Keyword::RECOVER, 50000, self::MAX],
        [Keyword::REDO_BUFFER_SIZE, 50106, self::MAX],
        [Keyword::REDO_LOG, 80021, self::MAX], // not documented as keyword. used in ENABLE INNODB REDO_LOG
        [Keyword::REDOFILE, 50106, 80003],
        [Keyword::REDUNDANT, 50000, self::MAX],
        [Keyword::REFERENCE, 80004, self::MAX],
        [Keyword::REGISTRATION, 80027, self::MAX],
        [Keyword::RELAY, 50503, self::MAX],
        [Keyword::RELAY_LOG_FILE, self::MIN, self::MAX],
        [Keyword::RELAY_LOG_POS, self::MIN, self::MAX],
        [Keyword::RELAY_THREAD, self::MIN, self::MAX],
        [Keyword::RELAYLOG, 50500, self::MAX],
        [Keyword::RELOAD, self::MIN, self::MAX],
        [Keyword::REMOVE, 50109, self::MAX],
        [Keyword::REMOTE, 80003, 80014],
        [Keyword::REORGANISE, self::MIN, 50106],
        [Keyword::REORGANIZE, 50106, self::MAX],
        [Keyword::REPAIR, self::MIN, self::MAX],
        [Keyword::REPEATABLE, self::MIN, self::MAX],
        [Keyword::REPLICA, 80022, self::MAX],
        [Keyword::REPLICAS, 80022, self::MAX],
        [Keyword::REPLICATE_DO_DB, 50703, self::MAX],
        [Keyword::REPLICATE_DO_TABLE, 50703, self::MAX],
        [Keyword::REPLICATE_IGNORE_DB, 50703, self::MAX],
        [Keyword::REPLICATE_IGNORE_TABLE, 50703, self::MAX],
        [Keyword::REPLICATE_REWRITE_DB, 50703, self::MAX],
        [Keyword::REPLICATE_WILD_DO_TABLE, 50703, self::MAX],
        [Keyword::REPLICATE_WILD_IGNORE_TABLE, 50703, self::MAX],
        [Keyword::REPLICATION, self::MIN, self::MAX],
        [Keyword::REQUIRE_ROW_FORMAT, 80019, self::MAX],
        [Keyword::REQUIRE_TABLE_PRIMARY_KEY_CHECK, 80020, self::MAX], // not listed
        [Keyword::RESET, self::MIN, self::MAX],
        [Keyword::RESOURCE, 80003, self::MAX],
        [Keyword::RESPECT, 80002, self::MAX],
        [Keyword::RESTART, 80004, self::MAX],
        [Keyword::RESTORE, self::MIN, self::MAX],
        [Keyword::RESUME, 50000, self::MAX],
        [Keyword::RETAIN, 80014, self::MAX],
        [Keyword::RETURNED_SQLSTATE, 50604, self::MAX],
        [Keyword::RETURNING, 80021, self::MAX],
        [Keyword::RETURNS, self::MIN, self::MAX],
        [Keyword::REUSE, 80003, self::MAX],
        [Keyword::REVERSE, 50600, self::MAX],
        [Keyword::ROLE, 80001, self::MAX],
        [Keyword::ROLLBACK, self::MIN, self::MAX],
        [Keyword::ROLLUP, self::MIN, self::MAX],
        [Keyword::ROTATE, 50711, self::MAX],
        [Keyword::ROUTINE, 50000, self::MAX],
        [Keyword::ROW, self::MIN, 80002],
        [Keyword::ROW_COUNT, 50604, self::MAX],
        [Keyword::ROW_FORMAT, self::MIN, self::MAX],
        [Keyword::ROWS, self::MIN, 80002],
        [Keyword::RTREE, self::MIN, self::MAX],
        [Keyword::SAVEPOINT, self::MIN, self::MAX],
        [Keyword::SECOND, self::MIN, self::MAX],
        [Keyword::SECONDARY, 80016, self::MAX],
        [Keyword::SECONDARY_ENGINE, 80013, self::MAX],
        [Keyword::SECONDARY_ENGINE_ATTRIBUTE, 80021, self::MAX],
        [Keyword::SECONDARY_LOAD, 80013, self::MAX],
        [Keyword::SECONDARY_UNLOAD, 80013, self::MAX],
        [Keyword::SECURITY, 50000, self::MAX],
        [Keyword::SERIAL, self::MIN, self::MAX],
        [Keyword::SERIALIZABLE, self::MIN, self::MAX],
        [Keyword::SERVER, 50115, self::MAX],
        [Keyword::SESSION, self::MIN, self::MAX],
        [Keyword::SHARE, self::MIN, self::MAX],
        [Keyword::SHUTDOWN, self::MIN, self::MAX],
        [Keyword::SCHEDULE, 50106, self::MAX],
        [Keyword::SCHEDULER, 50111, 50112],
        [Keyword::SCHEMA_NAME, 50500, self::MAX],
        [Keyword::SIGNED, self::MIN, self::MAX],
        [Keyword::SIMPLE, self::MIN, self::MAX],
        [Keyword::SKIP, 80001, self::MAX],
        [Keyword::SLAVE, self::MIN, self::MAX],
        [Keyword::SLOW, 50508, self::MAX],
        [Keyword::SLOW, 50601, self::MAX],
        [Keyword::SNAPSHOT, self::MIN, self::MAX],
        [Keyword::SOCKET, 50115, self::MAX],
        [Keyword::SOME, self::MIN, self::MAX],
        [Keyword::SONAME, self::MIN, self::MAX],
        [Keyword::SOUNDS, self::MIN, self::MAX],
        [Keyword::SOURCE, 50000, 50124],
        [Keyword::SOURCE, 80023, self::MAX],
        [Keyword::SOURCE_AUTO_POSITION, 80023, self::MAX],
        [Keyword::SOURCE_BIND, 80023, self::MAX],
        [Keyword::SOURCE_COMPRESSION_ALGORITHMS, 80023, self::MAX],
        [Keyword::SOURCE_CONNECT_RETRY, 80023, self::MAX],
        [Keyword::SOURCE_CONNECTION_AUTO_FAILOVER, 80023, self::MAX], // not documented as keyword
        [Keyword::SOURCE_DELAY, 80023, self::MAX],
        [Keyword::SOURCE_HEARTBEAT_PERIOD, 80023, self::MAX],
        [Keyword::SOURCE_HOST, 80023, self::MAX],
        [Keyword::SOURCE_LOG_FILE, 80023, self::MAX],
        [Keyword::SOURCE_LOG_POS, 80023, self::MAX],
        [Keyword::SOURCE_PASSWORD, 80023, self::MAX],
        [Keyword::SOURCE_PORT, 80023, self::MAX],
        [Keyword::SOURCE_PUBLIC_KEY_PATH, 80023, self::MAX],
        [Keyword::SOURCE_RETRY_COUNT, 80023, self::MAX],
        [Keyword::SOURCE_SSL, 80023, self::MAX],
        [Keyword::SOURCE_SSL_CA, 80023, self::MAX],
        [Keyword::SOURCE_SSL_CAPATH, 80023, self::MAX],
        [Keyword::SOURCE_SSL_CERT, 80023, self::MAX],
        [Keyword::SOURCE_SSL_CIPHER, 80023, self::MAX],
        [Keyword::SOURCE_SSL_CRL, 80023, self::MAX],
        [Keyword::SOURCE_SSL_CRLPATH, 80023, self::MAX],
        [Keyword::SOURCE_SSL_KEY, 80023, self::MAX],
        [Keyword::SOURCE_SSL_VERIFY_SERVER_CERT, 80023, self::MAX],
        [Keyword::SOURCE_TLS_CIPHERSUITES, 80023, self::MAX],
        [Keyword::SOURCE_TLS_VERSION, 80023, self::MAX],
        [Keyword::SOURCE_USER, 80023, self::MAX],
        [Keyword::SOURCE_ZSTD_COMPRESSION_LEVEL, 80023, self::MAX],
        [Keyword::SQL_AFTER_GTIDS, 50606, self::MAX],
        [Keyword::SQL_AFTER_MTS_GAPS, 50606, self::MAX],
        [Keyword::SQL_BEFORE_GTIDS, 50606, self::MAX],
        [Keyword::SQL_BUFFER_RESULT, self::MIN, self::MAX],
        [Keyword::SQL_CACHE, self::MIN, 80003],
        [Keyword::SQL_NO_CACHE, self::MIN, self::MAX],
        [Keyword::SQL_THREAD, self::MIN, self::MAX],
        [Keyword::SQL_TSI_DAY, 50000, self::MAX],
        [Keyword::SQL_TSI_FRAC_SECOND, 50000, 50503],
        [Keyword::SQL_TSI_HOUR, 50000, self::MAX],
        [Keyword::SQL_TSI_MINUTE, 50000, self::MAX],
        [Keyword::SQL_TSI_MONTH, 50000, self::MAX],
        [Keyword::SQL_TSI_QUARTER, 50000, self::MAX],
        [Keyword::SQL_TSI_SECOND, 50000, self::MAX],
        [Keyword::SQL_TSI_WEEK, 50000, self::MAX],
        [Keyword::SQL_TSI_YEAR, 50000, self::MAX],
        [Keyword::SRID, 80003, self::MAX],
        [Keyword::STACKED, 50700, self::MAX],
        [Keyword::START, self::MIN, self::MAX],
        [Keyword::STARTS, 50106, self::MAX],
        [Keyword::STATS_AUTO_RECALC, 50606, self::MAX],
        [Keyword::STATS_PERSISTENT, 50606, self::MAX],
        [Keyword::STATS_SAMPLE_PAGES, 50606, self::MAX],
        [Keyword::STATUS, self::MIN, self::MAX],
        [Keyword::STOP, self::MIN, self::MAX],
        [Keyword::STORAGE, self::MIN, self::MAX],
        [Keyword::STREAM, 80020, self::MAX],
        [Keyword::STRING, self::MIN, self::MAX],
        [Keyword::STRIPED, self::MIN, 50107],
        [Keyword::SUBCLASS_ORIGIN, 50500, self::MAX],
        [Keyword::SUBJECT, self::MIN, self::MAX],
        [Keyword::SUBPARTITION, 50100, self::MAX],
        [Keyword::SUBPARTITIONS, 50100, self::MAX],
        [Keyword::SUPER, self::MIN, self::MAX],
        [Keyword::SUSPEND, 50000, self::MAX],
        [Keyword::SWAPS, 50000, self::MAX],
        [Keyword::SWITCHES, 50000, self::MAX],
        [Keyword::TABLE_CHECKSUM, 50124, self::MAX],
        [Keyword::TABLE_NAME, 50500, self::MAX],
        [Keyword::TABLES, self::MIN, self::MAX],
        [Keyword::TABLESPACE, self::MIN, self::MAX],
        [Keyword::TEMPORARY, self::MIN, self::MAX],
        [Keyword::TEMPTABLE, 50000, self::MAX],
        [Keyword::TEXT, self::MIN, self::MAX],
        [Keyword::THAN, 50100, self::MAX],
        [Keyword::THREAD_PRIORITY, 80003, self::MAX],
        [Keyword::TIES, 80002, self::MAX],
        [Keyword::TIME, self::MIN, self::MAX],
        [Keyword::TIMESTAMP, self::MIN, self::MAX],
        [Keyword::TIMESTAMPADD, 50000, self::MAX],
        [Keyword::TIMESTAMPDIFF, 50000, self::MAX],
        [Keyword::TLS, 80021, self::MAX],
        [Keyword::TRANSACTION, self::MIN, self::MAX],
        [Keyword::TRANSACTIONAL, 50124, 50138],
        [Keyword::TRIGGERS, 50000, self::MAX],
        [Keyword::TRUNCATE, self::MIN, self::MAX],
        [Keyword::TYPE, self::MIN, self::MAX],
        [Keyword::TYPES, self::MIN, self::MAX],
        [Keyword::UNBOUNDED, 80002, self::MAX],
        [Keyword::UNCOMMITTED, self::MIN, self::MAX],
        [Keyword::UNDEFINED, 50000, self::MAX],
        [Keyword::UNDO_BUFFER_SIZE, 50106, self::MAX],
        [Keyword::UNDOFILE, 50106, self::MAX],
        [Keyword::UNICODE, self::MIN, self::MAX],
        [Keyword::UNINSTALL, 50100, self::MAX],
        [Keyword::UNKNOWN, 50000, self::MAX],
        [Keyword::UNREGISTER, 80027, self::MAX],
        [Keyword::UNTIL, self::MIN, self::MAX],
        [Keyword::UPGRADE, 50000, self::MAX],
        [Keyword::USE_FRM, self::MIN, self::MAX],
        [Keyword::USER, self::MIN, self::MAX],
        [Keyword::USER_RESOURCES, self::MIN, self::MAX],
        [Keyword::VALIDATION, 50705, self::MAX],
        [Keyword::VALUE, self::MIN, self::MAX],
        [Keyword::VARIABLES, self::MIN, self::MAX],
        [Keyword::VCPU, 80003, self::MAX],
        [Keyword::VIEW, 50000, self::MAX],
        [Keyword::VISIBLE, 80000, self::MAX],
        [Keyword::WAIT, 50106, self::MAX],
        [Keyword::WARNINGS, self::MIN, self::MAX],
        [Keyword::WEEK, 50000, self::MAX],
        [Keyword::WEIGHT_STRING, 50600, self::MAX],
        [Keyword::WITHOUT, 50705, self::MAX],
        [Keyword::WORK, self::MIN, self::MAX],
        [Keyword::WRAPPER, 50115, self::MAX],
        [Keyword::X509, self::MIN, self::MAX],
        [Keyword::XA, 50000, self::MAX],
        [Keyword::XID, 50705, self::MAX],
        [Keyword::XML, 50500, self::MAX],
        [Keyword::YEAR, self::MIN, self::MAX],
        [Keyword::ZONE, 80022, self::MAX],
    ];

    /** @var array<array{string, int, int}> */
    public $operators = [
        // assign
        [Operator::ASSIGN, self::MIN, self::MAX],

        // boolean
        [Operator::AND, self::MIN, self::MAX],
        [Operator::OR, self::MIN, self::MAX],
        [Operator::XOR, self::MIN, self::MAX],
        [Operator::NOT, self::MIN, self::MAX],
        [Operator::AMPERSANDS, self::MIN, self::MAX],
        [Operator::PIPES, self::MIN, self::MAX],
        [Operator::EXCLAMATION, self::MIN, self::MAX],

        // comparison
        [Operator::EQUAL, self::MIN, self::MAX],
        [Operator::NOT_EQUAL, self::MIN, self::MAX],
        [Operator::GREATER, self::MIN, self::MAX],
        [Operator::GREATER_OR_EQUAL, self::MIN, self::MAX],
        [Operator::LESS, self::MIN, self::MAX],
        [Operator::LESS_OR_EQUAL, self::MIN, self::MAX],
        [Operator::LESS_OR_GREATER, self::MIN, self::MAX],
        [Operator::SAFE_EQUAL, self::MIN, self::MAX],
        [Operator::BETWEEN, self::MIN, self::MAX],
        [Operator::NOT_BETWEEN, self::MIN, self::MAX],

        // arithmetic
        [Operator::PLUS, self::MIN, self::MAX],
        [Operator::MINUS, self::MIN, self::MAX],
        [Operator::MULTIPLY, self::MIN, self::MAX],
        [Operator::DIVIDE, self::MIN, self::MAX],
        [Operator::DIV, self::MIN, self::MAX],
        [Operator::MOD, self::MIN, self::MAX],
        [Operator::MODULO, self::MIN, self::MAX],

        // binary
        [Operator::BIT_AND, self::MIN, self::MAX],
        [Operator::BIT_INVERT, self::MIN, self::MAX],
        [Operator::BIT_OR, self::MIN, self::MAX],
        [Operator::BIT_XOR, self::MIN, self::MAX],
        [Operator::LEFT_SHIFT, self::MIN, self::MAX],
        [Operator::RIGHT_SHIFT, self::MIN, self::MAX],

        // test
        [Operator::IS, self::MIN, self::MAX],
        [Operator::IS_NOT, self::MIN, self::MAX],
        [Operator::LIKE, self::MIN, self::MAX],
        [Operator::NOT_LIKE, self::MIN, self::MAX],
        [Operator::ESCAPE, self::MIN, self::MAX],
        [Operator::REGEXP, self::MIN, self::MAX],
        [Operator::NOT_REGEXP, self::MIN, self::MAX],
        [Operator::RLIKE, self::MIN, self::MAX],
        [Operator::NOT_RLIKE, self::MIN, self::MAX],
        [Operator::SOUNDS_LIKE, self::MIN, self::MAX],

        // case
        [Operator::CASE, self::MIN, self::MAX],
        [Operator::WHEN, self::MIN, self::MAX],
        [Operator::THEN, self::MIN, self::MAX],
        [Operator::ELSE, self::MIN, self::MAX],
        [Operator::END, self::MIN, self::MAX],

        // set & quantifiers
        [Operator::IN, self::MIN, self::MAX],
        [Operator::NOT_IN, self::MIN, self::MAX],
        [Operator::ALL, self::MIN, self::MAX],
        [Operator::ANY, self::MIN, self::MAX],
        [Operator::EXISTS, self::MIN, self::MAX],
        [Operator::SOME, self::MIN, self::MAX],

        // collation
        [Operator::BINARY, self::MIN, self::MAX], // todo: removed in 80027, but fails tests on 80099 ^_^

        // JSON
        [Operator::JSON_EXTRACT, 50709, self::MAX],
        [Operator::JSON_EXTRACT_UNQUOTE, 50713, self::MAX],
        [Operator::MEMBER_OF, 80017, self::MAX],
    ];

    /** @var array<array{string, int, int}> */
    public $types = [
        // bitwise
        [BaseType::BIT, self::MIN, self::MAX],

        // integers
        [BaseType::TINYINT, self::MIN, self::MAX],
        [BaseType::SMALLINT, self::MIN, self::MAX],
        [BaseType::MEDIUMINT, self::MIN, self::MAX],
        [BaseType::INT, self::MIN, self::MAX],
        [BaseType::BIGINT, self::MIN, self::MAX],
        [BaseType::SERIAL, self::MIN, self::MAX],
        [BaseType::BOOL, self::MIN, self::MAX], // TINYINT
        [BaseType::BOOLEAN, self::MIN, self::MAX], // TINYINT
        [BaseType::MIDDLEINT, self::MIN, self::MAX], // MEDIUMINT
        [BaseType::INTEGER, self::MIN, self::MAX], // INT
        [BaseType::INT1, self::MIN, self::MAX], // TINYINT
        [BaseType::INT2, self::MIN, self::MAX], // SMALLINT
        [BaseType::INT3, self::MIN, self::MAX], // MEDIUMINT
        [BaseType::INT4, self::MIN, self::MAX], // INT
        [BaseType::INT8, self::MIN, self::MAX], // BIGINT

        // floats
        [BaseType::FLOAT, self::MIN, self::MAX],
        [BaseType::DOUBLE, self::MIN, self::MAX],
        [BaseType::REAL, self::MIN, self::MAX], // FLOAT/DOUBLE
        [BaseType::FLOAT4, self::MIN, self::MAX], // FLOAT
        [BaseType::FLOAT8, self::MIN, self::MAX], // DOUBLE

        // decimal
        [BaseType::DECIMAL, self::MIN, self::MAX],
        [BaseType::DEC, self::MIN, self::MAX], // DECIMAL
        [BaseType::NUMERIC, self::MIN, self::MAX], // DECIMAL
        [BaseType::FIXED, self::MIN, self::MAX], // DECIMAL

        // time
        [BaseType::YEAR, self::MIN, self::MAX],
        [BaseType::DATE, self::MIN, self::MAX],
        [BaseType::DATETIME, self::MIN, self::MAX],
        [BaseType::TIME, self::MIN, self::MAX],
        [BaseType::TIMESTAMP, self::MIN, self::MAX],

        // texts
        [BaseType::CHAR, self::MIN, self::MAX],
        [BaseType::VARCHAR, self::MIN, self::MAX],
        [BaseType::TINYTEXT, self::MIN, self::MAX],
        [BaseType::TEXT, self::MIN, self::MAX],
        [BaseType::MEDIUMTEXT, self::MIN, self::MAX],
        [BaseType::LONGTEXT, self::MIN, self::MAX],
        [BaseType::CHARACTER, self::MIN, self::MAX], // CHAR
        [BaseType::NCHAR, self::MIN, self::MAX], // CHAR
        [BaseType::NATIONAL_CHAR, self::MIN, self::MAX], // CHAR
        [BaseType::CHARACTER_VARYING, self::MIN, self::MAX], // VARCHAR
        [BaseType::NVARCHAR, self::MIN, self::MAX], // VARCHAR
        [BaseType::NATIONAL_VARCHAR, self::MIN, self::MAX], // VARCHAR
        [BaseType::LONG, self::MIN, self::MAX], // MEDIUMTEXT
        [BaseType::LONG_VARCHAR, self::MIN, self::MAX], // MEDIUMTEXT

        // binary
        [BaseType::BINARY, self::MIN, self::MAX],
        [BaseType::VARBINARY, self::MIN, self::MAX],
        [BaseType::TINYBLOB, self::MIN, self::MAX],
        [BaseType::BLOB, self::MIN, self::MAX],
        [BaseType::MEDIUMBLOB, self::MIN, self::MAX],
        [BaseType::LONGBLOB, self::MIN, self::MAX],
        [BaseType::CHAR_BYTE, self::MIN, self::MAX], // BINARY
        [BaseType::LONG_VARBINARY, self::MIN, self::MAX], // MEDIUMBLOB

        // sets
        [BaseType::ENUM, self::MIN, self::MAX],
        [BaseType::SET, self::MIN, self::MAX],

        // json
        [BaseType::JSON, self::MIN, self::MAX],

        // geometry
        [BaseType::GEOMETRY, self::MIN, self::MAX],
        [BaseType::POINT, self::MIN, self::MAX],
        [BaseType::LINESTRING, self::MIN, self::MAX],
        [BaseType::POLYGON, self::MIN, self::MAX],
        [BaseType::GEOMETRYCOLLECTION, self::MIN, self::MAX],
        [BaseType::MULTIPOINT, self::MIN, self::MAX],
        [BaseType::MULTILINESTRING, self::MIN, self::MAX],
        [BaseType::MULTIPOLYGON, self::MIN, self::MAX],
    ];

    /** @var array<array{string, int, int, 3?: int}> */
    public $functions = [
        // comparison
        [BuiltInFunction::COALESCE, self::MIN, self::MAX],
        [BuiltInFunction::GREATEST, self::MIN, self::MAX],
        [BuiltInFunction::INTERVAL, self::MIN, self::MAX],
        [BuiltInFunction::ISNULL, self::MIN, self::MAX],
        [BuiltInFunction::LEAST, self::MIN, self::MAX],
        [BuiltInFunction::STRCMP, self::MIN, self::MAX],

        // flow control
        [BuiltInFunction::IF, self::MIN, self::MAX],
        [BuiltInFunction::IFNULL, self::MIN, self::MAX],
        [BuiltInFunction::NULLIF, self::MIN, self::MAX],

        // type
        [BuiltInFunction::CAST, self::MIN, self::MAX],
        [BuiltInFunction::CONVERT, self::MIN, self::MAX],

        // strings
        [BuiltInFunction::ASCII, self::MIN, self::MAX],
        [BuiltInFunction::BIN, self::MIN, self::MAX],
        [BuiltInFunction::BIT_LENGTH, self::MIN, self::MAX],
        [BuiltInFunction::CHAR, self::MIN, self::MAX],
        [BuiltInFunction::CHAR_LENGTH, self::MIN, self::MAX],
        [BuiltInFunction::CHARACTER_LENGTH, self::MIN, self::MAX],
        [BuiltInFunction::CONCAT, self::MIN, self::MAX],
        [BuiltInFunction::CONCAT_WS, self::MIN, self::MAX],
        [BuiltInFunction::ELT, self::MIN, self::MAX],
        [BuiltInFunction::EXPORT_SET, self::MIN, self::MAX],
        [BuiltInFunction::FIELD, self::MIN, self::MAX],
        [BuiltInFunction::FIND_IN_SET, self::MIN, self::MAX],
        [BuiltInFunction::FORMAT, self::MIN, self::MAX],
        [BuiltInFunction::FROM_BASE64, self::MIN, self::MAX],
        [BuiltInFunction::HEX, self::MIN, self::MAX],
        [BuiltInFunction::INSERT, self::MIN, self::MAX],
        [BuiltInFunction::INSTR, self::MIN, self::MAX],
        [BuiltInFunction::LCASE, self::MIN, self::MAX],
        [BuiltInFunction::LEFT, self::MIN, self::MAX],
        [BuiltInFunction::LENGTH, self::MIN, self::MAX],
        [BuiltInFunction::LOAD_FILE, self::MIN, self::MAX],
        [BuiltInFunction::LOCATE, self::MIN, self::MAX],
        [BuiltInFunction::LOWER, self::MIN, self::MAX],
        [BuiltInFunction::LPAD, self::MIN, self::MAX],
        [BuiltInFunction::LTRIM, self::MIN, self::MAX],
        [BuiltInFunction::MAKE_SET, self::MIN, self::MAX],
        [BuiltInFunction::MID, self::MIN, self::MAX],
        [BuiltInFunction::OCT, self::MIN, self::MAX],
        [BuiltInFunction::OCTET_LENGTH, self::MIN, self::MAX],
        [BuiltInFunction::ORD, self::MIN, self::MAX],
        [BuiltInFunction::POSITION, self::MIN, self::MAX],
        [BuiltInFunction::QUOTE, self::MIN, self::MAX],
        [BuiltInFunction::REGEXP_INSTR, 80000, self::MAX],
        [BuiltInFunction::REGEXP_LIKE, 80000, self::MAX],
        [BuiltInFunction::REGEXP_REPLACE, 80000, self::MAX],
        [BuiltInFunction::REGEXP_SUBSTR, 80000, self::MAX],
        [BuiltInFunction::REPEAT, self::MIN, self::MAX],
        [BuiltInFunction::REPLACE, self::MIN, self::MAX],
        [BuiltInFunction::REVERSE, self::MIN, self::MAX],
        [BuiltInFunction::RIGHT, self::MIN, self::MAX],
        [BuiltInFunction::RPAD, self::MIN, self::MAX],
        [BuiltInFunction::RTRIM, self::MIN, self::MAX],
        [BuiltInFunction::SOUNDEX, self::MIN, self::MAX],
        [BuiltInFunction::SPACE, self::MIN, self::MAX],
        [BuiltInFunction::SUBSTR, self::MIN, self::MAX],
        [BuiltInFunction::SUBSTRING, self::MIN, self::MAX],
        [BuiltInFunction::SUBSTRING_INDEX, self::MIN, self::MAX],
        [BuiltInFunction::TO_BASE64, self::MIN, self::MAX],
        [BuiltInFunction::TRIM, self::MIN, self::MAX],
        [BuiltInFunction::UCASE, self::MIN, self::MAX],
        [BuiltInFunction::UNHEX, self::MIN, self::MAX],
        [BuiltInFunction::UPPER, self::MIN, self::MAX],
        [BuiltInFunction::WEIGHT_STRING, self::MIN, self::MAX],

        // XML
        [BuiltInFunction::ExtractValue, self::MIN, self::MAX],
        [BuiltInFunction::UpdateXML, self::MIN, self::MAX],

        // numeric
        [BuiltInFunction::ABS, self::MIN, self::MAX],
        [BuiltInFunction::ACOS, self::MIN, self::MAX],
        [BuiltInFunction::ASIN, self::MIN, self::MAX],
        [BuiltInFunction::ATAN, self::MIN, self::MAX],
        [BuiltInFunction::ATAN2, self::MIN, self::MAX],
        [BuiltInFunction::BIT_COUNT, self::MIN, self::MAX],
        [BuiltInFunction::CEIL, self::MIN, self::MAX],
        [BuiltInFunction::CEILING, self::MIN, self::MAX],
        [BuiltInFunction::CONV, self::MIN, self::MAX],
        [BuiltInFunction::COS, self::MIN, self::MAX],
        [BuiltInFunction::COT, self::MIN, self::MAX],
        [BuiltInFunction::CRC32, self::MIN, self::MAX],
        [BuiltInFunction::DEGREES, self::MIN, self::MAX],
        [BuiltInFunction::EXP, self::MIN, self::MAX],
        [BuiltInFunction::FLOOR, self::MIN, self::MAX],
        [BuiltInFunction::LN, self::MIN, self::MAX],
        [BuiltInFunction::LOG, self::MIN, self::MAX],
        [BuiltInFunction::LOG10, self::MIN, self::MAX],
        [BuiltInFunction::LOG2, self::MIN, self::MAX],
        [BuiltInFunction::MOD, self::MIN, self::MAX],
        [BuiltInFunction::PI, self::MIN, self::MAX],
        [BuiltInFunction::POW, self::MIN, self::MAX],
        [BuiltInFunction::POWER, self::MIN, self::MAX],
        [BuiltInFunction::RADIANS, self::MIN, self::MAX],
        [BuiltInFunction::RAND, self::MIN, self::MAX],
        [BuiltInFunction::ROUND, self::MIN, self::MAX],
        [BuiltInFunction::SIGN, self::MIN, self::MAX],
        [BuiltInFunction::SIN, self::MIN, self::MAX],
        [BuiltInFunction::SQRT, self::MIN, self::MAX],
        [BuiltInFunction::TAN, self::MIN, self::MAX],
        [BuiltInFunction::TRUNCATE, self::MIN, self::MAX],

        // date/time
        [BuiltInFunction::ADDDATE, self::MIN, self::MAX],
        [BuiltInFunction::ADDTIME, self::MIN, self::MAX],
        [BuiltInFunction::CONVERT_TZ, self::MIN, self::MAX],
        [BuiltInFunction::CURDATE, self::MIN, self::MAX],
        [BuiltInFunction::CURRENT_DATE, self::MIN, self::MAX],
        [BuiltInFunction::CURRENT_ROLE, self::MIN, self::MAX],
        [BuiltInFunction::CURRENT_TIME, self::MIN, self::MAX],
        [BuiltInFunction::CURRENT_TIMESTAMP, self::MIN, self::MAX],
        [BuiltInFunction::CURTIME, self::MIN, self::MAX],
        [BuiltInFunction::DATE, self::MIN, self::MAX],
        [BuiltInFunction::DATEDIFF, self::MIN, self::MAX],
        [BuiltInFunction::DATE_ADD, self::MIN, self::MAX],
        [BuiltInFunction::DATE_FORMAT, self::MIN, self::MAX],
        [BuiltInFunction::DATE_SUB, self::MIN, self::MAX],
        [BuiltInFunction::DAY, self::MIN, self::MAX],
        [BuiltInFunction::DAYNAME, self::MIN, self::MAX],
        [BuiltInFunction::DAYOFMONTH, self::MIN, self::MAX],
        [BuiltInFunction::DAYOFWEEK, self::MIN, self::MAX],
        [BuiltInFunction::DAYOFYEAR, self::MIN, self::MAX],
        [BuiltInFunction::EXTRACT, self::MIN, self::MAX],
        [BuiltInFunction::FROM_DAYS, self::MIN, self::MAX],
        [BuiltInFunction::FROM_UNIXTIME, self::MIN, self::MAX],
        [BuiltInFunction::GET_FORMAT, self::MIN, self::MAX],
        [BuiltInFunction::HOUR, self::MIN, self::MAX],
        [BuiltInFunction::LAST_DAY, self::MIN, self::MAX],
        [BuiltInFunction::LOCALTIME, self::MIN, self::MAX],
        [BuiltInFunction::LOCALTIMESTAMP, self::MIN, self::MAX],
        [BuiltInFunction::MAKEDATE, self::MIN, self::MAX],
        [BuiltInFunction::MAKETIME, self::MIN, self::MAX],
        [BuiltInFunction::MICROSECOND, self::MIN, self::MAX],
        [BuiltInFunction::MINUTE, self::MIN, self::MAX],
        [BuiltInFunction::MONTH, self::MIN, self::MAX],
        [BuiltInFunction::MONTHNAME, self::MIN, self::MAX],
        [BuiltInFunction::NOW, self::MIN, self::MAX],
        [BuiltInFunction::PERIOD_ADD, self::MIN, self::MAX],
        [BuiltInFunction::PERIOD_DIFF, self::MIN, self::MAX],
        [BuiltInFunction::QUARTER, self::MIN, self::MAX],
        [BuiltInFunction::SECOND, self::MIN, self::MAX],
        [BuiltInFunction::SEC_TO_TIME, self::MIN, self::MAX],
        [BuiltInFunction::STR_TO_DATE, self::MIN, self::MAX],
        [BuiltInFunction::SUBDATE, self::MIN, self::MAX],
        [BuiltInFunction::SUBTIME, self::MIN, self::MAX],
        [BuiltInFunction::SYSDATE, self::MIN, self::MAX],
        [BuiltInFunction::TIME, self::MIN, self::MAX],
        [BuiltInFunction::TIMEDIFF, self::MIN, self::MAX],
        [BuiltInFunction::TIMESTAMP, self::MIN, self::MAX],
        [BuiltInFunction::TIMESTAMPADD, self::MIN, self::MAX],
        [BuiltInFunction::TIMESTAMPDIFF, self::MIN, self::MAX],
        [BuiltInFunction::TIME_FORMAT, self::MIN, self::MAX],
        [BuiltInFunction::TIME_TO_SEC, self::MIN, self::MAX],
        [BuiltInFunction::TO_DAYS, self::MIN, self::MAX],
        [BuiltInFunction::TO_SECONDS, self::MIN, self::MAX],
        [BuiltInFunction::UNIX_TIMESTAMP, self::MIN, self::MAX],
        [BuiltInFunction::UTC_DATE, self::MIN, self::MAX],
        [BuiltInFunction::UTC_TIME, self::MIN, self::MAX],
        [BuiltInFunction::UTC_TIMESTAMP, self::MIN, self::MAX],
        [BuiltInFunction::WEEK, self::MIN, self::MAX],
        [BuiltInFunction::WEEKDAY, self::MIN, self::MAX],
        [BuiltInFunction::WEEKOFYEAR, self::MIN, self::MAX],
        [BuiltInFunction::YEAR, self::MIN, self::MAX],
        [BuiltInFunction::YEARWEEK, self::MIN, self::MAX],

        // encryption & compression
        [BuiltInFunction::AES_DECRYPT, self::MIN, self::MAX],
        [BuiltInFunction::AES_ENCRYPT, self::MIN, self::MAX],
        [BuiltInFunction::ASYMMETRIC_DECRYPT, self::MIN, self::MAX],
        [BuiltInFunction::ASYMMETRIC_DERIVE, self::MIN, self::MAX],
        [BuiltInFunction::ASYMMETRIC_ENCRYPT, self::MIN, self::MAX],
        [BuiltInFunction::ASYMMETRIC_SIGN, self::MIN, self::MAX],
        [BuiltInFunction::ASYMMETRIC_VERIFY, self::MIN, self::MAX],
        [BuiltInFunction::COMPRESS, self::MIN, self::MAX],
        [BuiltInFunction::CREATE_ASYMMETRIC_PRIV_KEY, self::MIN, self::MAX],
        [BuiltInFunction::CREATE_ASYMMETRIC_PUB_KEY, self::MIN, self::MAX],
        [BuiltInFunction::CREATE_DH_PARAMETERS, self::MIN, self::MAX],
        [BuiltInFunction::CREATE_DIGEST, self::MIN, self::MAX],
        [BuiltInFunction::DECODE, self::MIN, self::MAX, 50700],
        [BuiltInFunction::DES_DECRYPT, self::MIN, 80000, 50700],
        [BuiltInFunction::DES_ENCRYPT, self::MIN, 80000, 50700],
        [BuiltInFunction::ENCODE, self::MIN, self::MAX, 50700],
        [BuiltInFunction::ENCRYPT, self::MIN, 80000, 50700],
        [BuiltInFunction::MD5, self::MIN, self::MAX],
        [BuiltInFunction::PASSWORD, self::MIN, 80000, 50700],
        [BuiltInFunction::RANDOM_BYTES, 50617, self::MAX],
        [BuiltInFunction::SHA, self::MIN, self::MAX],
        [BuiltInFunction::SHA1, self::MIN, self::MAX],
        [BuiltInFunction::SHA2, self::MIN, self::MAX],
        [BuiltInFunction::UNCOMPRESS, self::MIN, self::MAX],
        [BuiltInFunction::UNCOMPRESSED_LENGTH, self::MIN, self::MAX],
        [BuiltInFunction::VALIDATE_PASSWORD_STRENGTH, self::MIN, self::MAX],

        // information
        [BuiltInFunction::BENCHMARK, self::MIN, self::MAX],
        [BuiltInFunction::CHARSET, self::MIN, self::MAX],
        [BuiltInFunction::COERCIBILITY, self::MIN, self::MAX],
        [BuiltInFunction::COLLATION, self::MIN, self::MAX],
        [BuiltInFunction::CONNECTION_ID, self::MIN, self::MAX],
        [BuiltInFunction::CURRENT_ROLE, 80000, self::MAX],
        [BuiltInFunction::CURRENT_USER, self::MIN, self::MAX],
        [BuiltInFunction::DATABASE, self::MIN, self::MAX],
        [BuiltInFunction::FOUND_ROWS, self::MIN, self::MAX],
        [BuiltInFunction::LAST_INSERT_ID, self::MIN, self::MAX],
        [BuiltInFunction::ROLES_GRAPHML, self::MIN, self::MAX],
        [BuiltInFunction::ROW_COUNT, self::MIN, self::MAX],
        [BuiltInFunction::SCHEMA, self::MIN, self::MAX],
        [BuiltInFunction::SESSION_USER, self::MIN, self::MAX],
        [BuiltInFunction::SYSTEM_USER, self::MIN, self::MAX],
        [BuiltInFunction::USER, self::MIN, self::MAX],
        [BuiltInFunction::VERSION, self::MIN, self::MAX],

        // GTID
        [BuiltInFunction::GTID_SUBSET, self::MIN, self::MAX],
        [BuiltInFunction::GTID_SUBTRACT, self::MIN, self::MAX],
        [BuiltInFunction::WAIT_FOR_EXECUTED_GTID_SET, self::MIN, self::MAX],
        [BuiltInFunction::WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS, 80018, self::MAX],

        // performance_schema
        [BuiltInFunction::FORMAT_BYTES, 80016, self::MAX],
        [BuiltInFunction::FORMAT_PICO_TIME, 80016, self::MAX],
        [BuiltInFunction::PS_CURRENT_THREAD_ID, 80016, self::MAX],
        [BuiltInFunction::PS_THREAD_ID, 80016, self::MAX],

        // misc
        [BuiltInFunction::BIN_TO_UUID, self::MIN, self::MAX],
        [BuiltInFunction::DEFAULT, self::MIN, self::MAX],
        [BuiltInFunction::GET_LOCK, self::MIN, self::MAX],
        [BuiltInFunction::GROUPING, self::MIN, self::MAX],
        [BuiltInFunction::ICU_VERSION, 80000, self::MAX],
        [BuiltInFunction::INET6_ATON, self::MIN, self::MAX],
        [BuiltInFunction::INET6_NTOA, self::MIN, self::MAX],
        [BuiltInFunction::INET_ATON, self::MIN, self::MAX],
        [BuiltInFunction::INET_NTOA, self::MIN, self::MAX],
        [BuiltInFunction::IS_FREE_LOCK, self::MIN, self::MAX],
        [BuiltInFunction::IS_IPV4, self::MIN, self::MAX],
        [BuiltInFunction::IS_IPV4_COMPAT, self::MIN, self::MAX],
        [BuiltInFunction::IS_IPV4_MAPPED, self::MIN, self::MAX],
        [BuiltInFunction::IS_IPV6, self::MIN, self::MAX],
        [BuiltInFunction::IS_USED_LOCK, self::MIN, self::MAX],
        [BuiltInFunction::IS_UUID, self::MIN, self::MAX],
        [BuiltInFunction::MASTER_POS_WAIT, self::MIN, self::MAX, 80026],
        [BuiltInFunction::NAME_CONST, self::MIN, self::MAX],
        [BuiltInFunction::RELEASE_ALL_LOCKS, self::MIN, self::MAX],
        [BuiltInFunction::RELEASE_LOCK, self::MIN, self::MAX],
        [BuiltInFunction::SLEEP, self::MIN, self::MAX],
        [BuiltInFunction::SOURCE_POS_WAIT, 80026, self::MAX],
        [BuiltInFunction::STATEMENT_DIGEST, 80000, self::MAX],
        [BuiltInFunction::STATEMENT_DIGEST_NEXT, 80000, self::MAX],
        [BuiltInFunction::UUID, self::MIN, self::MAX],
        [BuiltInFunction::UUID_SHORT, self::MIN, self::MAX],
        [BuiltInFunction::UUID_TO_BIN, self::MIN, self::MAX],
        [BuiltInFunction::VALUES, self::MIN, self::MAX],

        // aggregate functions
        [BuiltInFunction::ANY_VALUE, self::MIN, self::MAX],
        [BuiltInFunction::AVG, self::MIN, self::MAX],
        [BuiltInFunction::BIT_AND, self::MIN, self::MAX],
        [BuiltInFunction::BIT_OR, self::MIN, self::MAX],
        [BuiltInFunction::BIT_XOR, self::MIN, self::MAX],
        [BuiltInFunction::COUNT, self::MIN, self::MAX],
        [BuiltInFunction::COUNT_DISTINCT, self::MIN, self::MAX],
        [BuiltInFunction::GROUP_CONCAT, self::MIN, self::MAX],
        [BuiltInFunction::JSON_ARRAYAGG, 50722, self::MAX],
        [BuiltInFunction::JSON_OBJECTAGG, 50722, self::MAX],
        [BuiltInFunction::MAX, self::MIN, self::MAX],
        [BuiltInFunction::MIN, self::MIN, self::MAX],
        [BuiltInFunction::STD, self::MIN, self::MAX],
        [BuiltInFunction::STDDEV, self::MIN, self::MAX],
        [BuiltInFunction::STDDEV_POP, self::MIN, self::MAX],
        [BuiltInFunction::STDDEV_SAMP, self::MIN, self::MAX],
        [BuiltInFunction::SUM, self::MIN, self::MAX],
        [BuiltInFunction::VAR_POP, self::MIN, self::MAX],
        [BuiltInFunction::VAR_SAMP, self::MIN, self::MAX],
        [BuiltInFunction::VARIANCE, self::MIN, self::MAX],

        // window functions
        [BuiltInFunction::CUME_DIST, self::MIN, self::MAX],
        [BuiltInFunction::DENSE_RANK, self::MIN, self::MAX],
        [BuiltInFunction::FIRST_VALUE, self::MIN, self::MAX],
        [BuiltInFunction::LAG, self::MIN, self::MAX],
        [BuiltInFunction::LAST_VALUE, self::MIN, self::MAX],
        [BuiltInFunction::LEAD, self::MIN, self::MAX],
        [BuiltInFunction::NTH_VALUE, self::MIN, self::MAX],
        [BuiltInFunction::NTILE, self::MIN, self::MAX],
        [BuiltInFunction::PERCENT_RANK, self::MIN, self::MAX],
        [BuiltInFunction::RANK, self::MIN, self::MAX],
        [BuiltInFunction::ROW_NUMBER, self::MIN, self::MAX],

        // JSON
        [BuiltInFunction::JSON_APPEND, 50700, 80000, 50700],
        [BuiltInFunction::JSON_ARRAY, 50700, self::MAX],
        [BuiltInFunction::JSON_ARRAY_APPEND, 50709, self::MAX],
        [BuiltInFunction::JSON_ARRAY_INSERT, 50700, self::MAX],
        [BuiltInFunction::JSON_CONTAINS, 50700, self::MAX],
        [BuiltInFunction::JSON_CONTAINS_PATH, 50700, self::MAX],
        [BuiltInFunction::JSON_DEPTH, 50700, self::MAX],
        [BuiltInFunction::JSON_EXTRACT, 50700, self::MAX],
        [BuiltInFunction::JSON_INSERT, 50700, self::MAX],
        [BuiltInFunction::JSON_KEYS, 50700, self::MAX],
        [BuiltInFunction::JSON_LENGTH, 50700, self::MAX],
        [BuiltInFunction::JSON_MERGE, 50700, self::MAX, 50722],
        [BuiltInFunction::JSON_MERGE_PATCH, 50722, self::MAX],
        [BuiltInFunction::JSON_MERGE_PRESERVE, 50722, self::MAX],
        [BuiltInFunction::JSON_OBJECT, 50700, self::MAX],
        [BuiltInFunction::JSON_OVERLAPS, 80017, self::MAX],
        [BuiltInFunction::JSON_PRETTY, 50722, self::MAX],
        [BuiltInFunction::JSON_QUOTE, 50700, self::MAX],
        [BuiltInFunction::JSON_REMOVE, 50700, self::MAX],
        [BuiltInFunction::JSON_REPLACE, 50700, self::MAX],
        [BuiltInFunction::JSON_SCHEMA_VALID, 80017, self::MAX],
        [BuiltInFunction::JSON_SCHEMA_VALIDATION_REPORT, 80017, self::MAX],
        [BuiltInFunction::JSON_SEARCH, 50700, self::MAX],
        [BuiltInFunction::JSON_SET, 50700, self::MAX],
        [BuiltInFunction::JSON_STORAGE_FREE, 80000, self::MAX],
        [BuiltInFunction::JSON_STORAGE_SIZE, 50722, self::MAX],
        [BuiltInFunction::JSON_TABLE, 80000, self::MAX],
        [BuiltInFunction::JSON_TYPE, 50700, self::MAX],
        [BuiltInFunction::JSON_UNQUOTE, 50700, self::MAX],
        [BuiltInFunction::JSON_VALID, 50700, self::MAX],
        [BuiltInFunction::JSON_VALUE, 80021, self::MAX],

        // spatial
        [BuiltInFunction::GeometryCollection, self::MIN, self::MAX],
        [BuiltInFunction::LineString, self::MIN, self::MAX],
        [BuiltInFunction::MBRContains, self::MIN, self::MAX],
        [BuiltInFunction::MBRCoveredBy, self::MIN, self::MAX],
        [BuiltInFunction::MBRCovers, self::MIN, self::MAX],
        [BuiltInFunction::MBRDisjoint, self::MIN, self::MAX],
        [BuiltInFunction::MBREquals, self::MIN, self::MAX],
        [BuiltInFunction::MBRIntersects, self::MIN, self::MAX],
        [BuiltInFunction::MBROverlaps, self::MIN, self::MAX],
        [BuiltInFunction::MBRTouches, self::MIN, self::MAX],
        [BuiltInFunction::MBRWithin, self::MIN, self::MAX],
        [BuiltInFunction::MultiLineString, self::MIN, self::MAX],
        [BuiltInFunction::MultiPoint, self::MIN, self::MAX],
        [BuiltInFunction::MultiPolygon, self::MIN, self::MAX],
        [BuiltInFunction::Point, self::MIN, self::MAX],
        [BuiltInFunction::Polygon, self::MIN, self::MAX],
        [BuiltInFunction::ST_Area, self::MIN, self::MAX],
        [BuiltInFunction::ST_AsBinary, self::MIN, self::MAX],
        [BuiltInFunction::ST_AsGeoJSON, self::MIN, self::MAX],
        [BuiltInFunction::ST_AsText, self::MIN, self::MAX],
        [BuiltInFunction::ST_AsWKT, self::MIN, self::MAX],
        [BuiltInFunction::ST_Buffer, self::MIN, self::MAX],
        [BuiltInFunction::ST_Buffer_Strategy, self::MIN, self::MAX],
        [BuiltInFunction::ST_Centroid, self::MIN, self::MAX],
        [BuiltInFunction::ST_Collect, 80024, self::MAX],
        [BuiltInFunction::ST_Contains, self::MIN, self::MAX],
        [BuiltInFunction::ST_ConvexHull, self::MIN, self::MAX],
        [BuiltInFunction::ST_Crosses, self::MIN, self::MAX],
        [BuiltInFunction::ST_Difference, self::MIN, self::MAX],
        [BuiltInFunction::ST_Dimension, self::MIN, self::MAX],
        [BuiltInFunction::ST_Disjoint, self::MIN, self::MAX],
        [BuiltInFunction::ST_Distance, self::MIN, self::MAX],
        [BuiltInFunction::ST_Distance_Sphere, self::MIN, self::MAX],
        [BuiltInFunction::ST_EndPoint, self::MIN, self::MAX],
        [BuiltInFunction::ST_Envelope, self::MIN, self::MAX],
        [BuiltInFunction::ST_Equals, self::MIN, self::MAX],
        [BuiltInFunction::ST_ExteriorRing, self::MIN, self::MAX],
        [BuiltInFunction::ST_FrechetDistance, 80023, self::MAX],
        [BuiltInFunction::ST_GeoHash, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeomCollFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeomCollFromTxt, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeomCollFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeomFromGeoJSON, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeomFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeomFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeometryCollectionFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeometryCollectionFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeometryFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeometryFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeometryN, self::MIN, self::MAX],
        [BuiltInFunction::ST_GeometryType, self::MIN, self::MAX],
        [BuiltInFunction::ST_HausdorffDistance, 80023, self::MAX],
        [BuiltInFunction::ST_InteriorRingN, self::MIN, self::MAX],
        [BuiltInFunction::ST_Intersection, self::MIN, self::MAX],
        [BuiltInFunction::ST_Intersects, self::MIN, self::MAX],
        [BuiltInFunction::ST_IsClosed, self::MIN, self::MAX],
        [BuiltInFunction::ST_IsEmpty, self::MIN, self::MAX],
        [BuiltInFunction::ST_IsSimple, self::MIN, self::MAX],
        [BuiltInFunction::ST_IsValid, self::MIN, self::MAX],
        [BuiltInFunction::ST_LatFromGeoHash, self::MIN, self::MAX],
        [BuiltInFunction::ST_Latitude, 80012, self::MAX],
        [BuiltInFunction::ST_Length, self::MIN, self::MAX],
        [BuiltInFunction::ST_LineFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_LineFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_LineInterpolatePoint, 80024, self::MAX],
        [BuiltInFunction::ST_LineInterpolatePoints, 80024, self::MAX],
        [BuiltInFunction::ST_LineStringFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_LineStringFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_LongFromGeoHash, self::MIN, self::MAX],
        [BuiltInFunction::ST_Longitude, 80012, self::MAX],
        [BuiltInFunction::ST_MLineFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_MLineFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_MPointFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_MPointFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_MPolyFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_MPolyFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_MakeEnvelope, self::MIN, self::MAX],
        [BuiltInFunction::ST_MultiLineStringFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_MultiLineStringFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_MultiPointFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_MultiPointFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_MultiPolygonFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_MultiPolygonFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_NumGeometries, self::MIN, self::MAX],
        [BuiltInFunction::ST_NumInteriorRing, self::MIN, self::MAX],
        [BuiltInFunction::ST_NumInteriorRings, self::MIN, self::MAX],
        [BuiltInFunction::ST_NumPoints, self::MIN, self::MAX],
        [BuiltInFunction::ST_Overlaps, self::MIN, self::MAX],
        [BuiltInFunction::ST_PointAtDistance, 80024, self::MAX],
        [BuiltInFunction::ST_PointFromGeoHash, self::MIN, self::MAX],
        [BuiltInFunction::ST_PointFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_PointFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_PointN, self::MIN, self::MAX],
        [BuiltInFunction::ST_PolyFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_PolyFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_PolygonFromText, self::MIN, self::MAX],
        [BuiltInFunction::ST_PolygonFromWKB, self::MIN, self::MAX],
        [BuiltInFunction::ST_SRID, self::MIN, self::MAX],
        [BuiltInFunction::ST_Simplify, self::MIN, self::MAX],
        [BuiltInFunction::ST_StartPoint, self::MIN, self::MAX],
        [BuiltInFunction::ST_SwapXY, self::MIN, self::MAX],
        [BuiltInFunction::ST_SymDifference, self::MIN, self::MAX],
        [BuiltInFunction::ST_Touches, self::MIN, self::MAX],
        [BuiltInFunction::ST_Transform, 80013, self::MAX],
        [BuiltInFunction::ST_Union, self::MIN, self::MAX],
        [BuiltInFunction::ST_Validate, self::MIN, self::MAX],
        [BuiltInFunction::ST_Within, self::MIN, self::MAX],
        [BuiltInFunction::ST_X, self::MIN, self::MAX],
        [BuiltInFunction::ST_Y, self::MIN, self::MAX],

        // old spatial
        [BuiltInFunction::Area, self::MIN, 80000, 50700],
        [BuiltInFunction::AsBinary, self::MIN, 80000, 50700],
        [BuiltInFunction::AsText, self::MIN, 80000, 50700],
        [BuiltInFunction::AsWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::AsWKT, self::MIN, 80000, 50700],
        [BuiltInFunction::Buffer, self::MIN, 80000, 50700],
        [BuiltInFunction::Centroid, self::MIN, 80000, 50700],
        [BuiltInFunction::Contains, self::MIN, 80000, 50700],
        [BuiltInFunction::ConvexHull, self::MIN, 80000, 50700],
        [BuiltInFunction::Crosses, self::MIN, 80000, 50700],
        [BuiltInFunction::Dimension, self::MIN, 80000, 50700],
        [BuiltInFunction::Disjoint, self::MIN, 80000, 50700],
        [BuiltInFunction::Distance, self::MIN, 80000, 50700],
        [BuiltInFunction::EndPoint, self::MIN, 80000, 50700],
        [BuiltInFunction::Envelope, self::MIN, 80000, 50700],
        [BuiltInFunction::Equals, self::MIN, 80000, 50700],
        [BuiltInFunction::ExteriorRing, self::MIN, 80000, 50700],
        [BuiltInFunction::GeomCollFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::GeomCollFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::GeometryCollectionFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::GeometryCollectionFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::GeometryFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::GeometryFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::GeometryN, self::MIN, 80000, 50700],
        [BuiltInFunction::GeometryType, self::MIN, 80000, 50700],
        [BuiltInFunction::GeomFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::GeomFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::GLength, self::MIN, 80000, 50700],
        [BuiltInFunction::InteriorRingN, self::MIN, 80000, 50700],
        [BuiltInFunction::Intersects, self::MIN, 80000, 50700],
        [BuiltInFunction::IsClosed, self::MIN, 80000, 50700],
        [BuiltInFunction::IsEmpty, self::MIN, 80000, 50700],
        [BuiltInFunction::IsSimple, self::MIN, 80000, 50700],
        [BuiltInFunction::LineFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::LineFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::LineStringFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::LineStringFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::MLineFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::MLineFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::MPointFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::MPointFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::MPolyFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::MPolyFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::MultiLineStringFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::MultiLineStringFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::MultiPointFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::MultiPointFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::MultiPolygonFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::MultiPolygonFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::NumGeometries, self::MIN, 80000, 50700],
        [BuiltInFunction::NumInteriorRings, self::MIN, 80000, 50700],
        [BuiltInFunction::NumPoints, self::MIN, 80000, 50700],
        [BuiltInFunction::Overlaps, self::MIN, 80000, 50700],
        [BuiltInFunction::PointFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::PointFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::PointN, self::MIN, 80000, 50700],
        [BuiltInFunction::PolyFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::PolyFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::PolygonFromText, self::MIN, 80000, 50700],
        [BuiltInFunction::PolygonFromWKB, self::MIN, 80000, 50700],
        [BuiltInFunction::SRID, self::MIN, 80000, 50700],
        [BuiltInFunction::StartPoint, self::MIN, 80000, 50700],
        [BuiltInFunction::Touches, self::MIN, 80000, 50700],
        [BuiltInFunction::Within, self::MIN, 80000, 50700],
        [BuiltInFunction::X, self::MIN, 80000, 50700],
        [BuiltInFunction::Y, self::MIN, 80000, 50700],
    ];

    /** @var array<array{string, int, int}> */
    public $variables = [
        // todo: variables
    ];

    /** @var array<array{class-string, int, int}> */
    public $preparableCommands = [
        // https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html (terribly incomplete)
        [AlterTableCommand::class, self::MIN, self::MAX],
        [AlterUserCommand::class, self::MIN, self::MAX],
        [AnalyzeTablesCommand::class, self::MIN, self::MAX],
        [AnalyzeTableDropHistogramCommand::class, self::MIN, self::MAX],
        [AnalyzeTableUpdateHistogramCommand::class, self::MIN, self::MAX],
        [CacheIndexCommand::class, self::MIN, self::MAX],
        [CallCommand::class, self::MIN, self::MAX],
        [ChangeMasterToCommand::class, self::MIN, self::MAX],
        [ChecksumTableCommand::class, self::MIN, self::MAX],
        [CommitCommand::class, self::MIN, self::MAX],
        [CreateIndexCommand::class, self::MIN, self::MAX],
        [CreateSchemaCommand::class, self::MIN, self::MAX],
        [CreateTableCommand::class, self::MIN, self::MAX],
        [CreateTableLikeCommand::class, self::MIN, self::MAX],
        [CreateUserCommand::class, self::MIN, self::MAX],
        [CreateViewCommand::class, self::MIN, self::MAX],
        [DeleteCommand::class, self::MIN, self::MAX],
        [DescribeTableCommand::class, self::MIN, self::MAX],
        [DoCommand::class, self::MIN, self::MAX],
        [DropIndexCommand::class, self::MIN, self::MAX],
        [DropSchemaCommand::class, self::MIN, self::MAX],
        [DropTableCommand::class, self::MIN, self::MAX],
        [DropUserCommand::class, self::MIN, self::MAX],
        [DropViewCommand::class, self::MIN, self::MAX],
        [ExplainStatementCommand::class, self::MIN, self::MAX],
        [FlushCommand::class, self::MIN, self::MAX],
        [FlushTablesCommand::class, self::MIN, self::MAX],
        [GrantCommand::class, self::MIN, self::MAX],
        [InsertCommand::class, self::MIN, self::MAX],
        [InsertSelectCommand::class, self::MIN, self::MAX],
        [InsertSetCommand::class, self::MIN, self::MAX],
        [InsertValuesCommand::class, self::MIN, self::MAX],
        [InstallPluginCommand::class, self::MIN, self::MAX],
        [KillCommand::class, self::MIN, self::MAX],
        [LoadIndexIntoCacheCommand::class, self::MIN, self::MAX],
        [OptimizeTableCommand::class, self::MIN, self::MAX],
        [ParenthesizedQueryExpression::class, self::MIN, self::MAX],
        [RenameTableCommand::class, self::MIN, self::MAX],
        [RenameUserCommand::class, self::MIN, self::MAX],
        [RepairTableCommand::class, self::MIN, self::MAX],
        [ReplaceSelectCommand::class, self::MIN, self::MAX],
        [ReplaceSetCommand::class, self::MIN, self::MAX],
        [ReplaceValuesCommand::class, self::MIN, self::MAX],
        [ResetMasterCommand::class, self::MIN, self::MAX],
        [ResetReplicaCommand::class, self::MIN, self::MAX],
        [ResetSlaveCommand::class, self::MIN, self::MAX],
        [RevokeAllCommand::class, self::MIN, self::MAX],
        [RevokeCommand::class, self::MIN, self::MAX],
        [RevokeProxyCommand::class, self::MIN, self::MAX],
        [RevokeRoleCommand::class, self::MIN, self::MAX],
        [RollbackCommand::class, self::MIN, self::MAX],
        [SelectCommand::class, self::MIN, self::MAX],
        [SetVariablesCommand::class, self::MIN, self::MAX],
        [SetNamesCommand::class, self::MIN, self::MAX],
        [SetPasswordCommand::class, self::MIN, self::MAX],
        [SetRoleCommand::class, self::MIN, self::MAX],
        [ShowBinaryLogsCommand::class, self::MIN, self::MAX],
        [ShowBinlogEventsCommand::class, self::MIN, self::MAX],
        [ShowCharacterSetCommand::class, self::MIN, self::MAX],
        [ShowCollationCommand::class, self::MIN, self::MAX],
        [ShowColumnsCommand::class, self::MIN, self::MAX],
        [ShowCreateEventCommand::class, self::MIN, self::MAX],
        [ShowCreateFunctionCommand::class, self::MIN, self::MAX],
        [ShowCreateProcedureCommand::class, self::MIN, self::MAX],
        [ShowProcessListCommand::class, self::MIN, self::MAX],
        [ShowCreateSchemaCommand::class, self::MIN, self::MAX],
        [ShowCreateTableCommand::class, self::MIN, self::MAX],
        [ShowCreateTriggerCommand::class, self::MIN, self::MAX],
        [ShowCreateViewCommand::class, self::MIN, self::MAX],
        [ShowEngineCommand::class, self::MIN, self::MAX],
        [ShowEnginesCommand::class, self::MIN, self::MAX],
        [ShowEventsCommand::class, self::MIN, self::MAX],
        [ShowFunctionStatusCommand::class, self::MIN, self::MAX],
        [ShowGrantsCommand::class, self::MIN, self::MAX],
        [ShowIndexesCommand::class, self::MIN, self::MAX],
        [ShowMasterStatusCommand::class, self::MIN, self::MAX],
        [ShowOpenTablesCommand::class, self::MIN, self::MAX],
        [ShowProcedureStatusCommand::class, self::MIN, self::MAX],
        [ShowProfileCommand::class, self::MIN, self::MAX],
        [ShowReplicaStatusCommand::class, self::MIN, self::MAX],
        [ShowSchemasCommand::class, self::MIN, self::MAX],
        [ShowSlaveStatusCommand::class, self::MIN, self::MAX],
        [ShowStatusCommand::class, self::MIN, self::MAX],
        [ShowTablesCommand::class, self::MIN, self::MAX],
        [ShowTableStatusCommand::class, self::MIN, self::MAX],
        [ShowTriggersCommand::class, self::MIN, self::MAX],
        [ShowVariablesCommand::class, self::MIN, self::MAX],
        [StartReplicaCommand::class, self::MIN, self::MAX],
        [StartSlaveCommand::class, self::MIN, self::MAX],
        [StopReplicaCommand::class, self::MIN, self::MAX],
        [StopSlaveCommand::class, self::MIN, self::MAX],
        [TableCommand::class, self::MIN, self::MAX],
        [TruncateTableCommand::class, self::MIN, self::MAX],
        [UnionExpression::class, self::MIN, self::MAX],
        [UninstallPluginCommand::class, self::MIN, self::MAX],
        [UpdateCommand::class, self::MIN, self::MAX],
        [ValuesCommand::class, self::MIN, self::MAX],
    ];

}
